### ISSUE TITLE
What is the advantage of Regret Matching against exp3(Hedge) as policy improvement methods?

### ISSUE THREAD

**Issue by szrlee** [deepmind/open_spiel#102]
What is the advantage of regret matching against exp3 as policy improvement methods?
What will happen if we replace RM in all CFR variants by Hedge?

**Comment by lanctot** [comment]
That is a _wonderful_ question, one I got in my thesis defense and several times from reviewers!

BTW: I assume you mean in the context of CFR. 

There are several reasons:

1. RM is parameter-free. No learning rate to have to tune. In particular, in the case of Hedge/Exp3, their regret convergence rates depend critically on this learning rate (and for the optimal one, you need to know the number of iterations in advance or use the doubling tricks). They have a "worst-case learning rate" of 1/sqrt(T) but it simply hasn't worked as well as RM in practice, though @noambrown managed to get them to work ok with regret-based pruning: https://www.cs.cmu.edu/~noamb/papers/17-AAAI-Prune.pdf

2. This is maybe the biggest one: it lets you do cuts. Since regret matching assigns 0 to negative regret actions and the counterfactual regret is a product of opponent-weighted reach and the average strategy is a product of my-weighted reach, you can cut out large subtrees under those actions. In OpenSpiel, the place we do this is here: https://github.com/deepmind/open_spiel/blob/b46c34cc94111fca1f6bb7b943e0200ca61c72ab/open_spiel/algorithms/cfr.cc#L194 (note that with a less general CFR implementation, like if you assume two-player zero-sum, you can do even more cuts because you can do the regret pass for player i while doing the average strategy pass for player -i and cut when only one of the reaches is zero).

In practice, what little theoretically-motivated benefited comes from using exponential weights algorithm has been completely masked by the practical benefits of those two above. That said, a few follow-up comments (some of this is different when you're looking at relationships to RL algorithms):

3. Point #2 is not as well-justified when you're doing sampling, since there are not cuts. My attempt to get MCCFR to work with Exp3 did not fair well, but I didn't try as hard as Noam!

4. The policy gradient algorithms we've been working on over the past few years (RPG, ED, NeuRD) are much closer to CFR(Hedge) than they are to CFR(RM), which is interesting. And actually NeuRD is exactly CFR(Hedge) but with function approximation.

Finally, it turns out RM and Hedge are related in an even more fundamental way :) @dmorrill10 has worked this out but it is not public yet. So, in the end, it's quite a deep question, and we're still working on it!

**Comment by noambrown** [comment]
(2) isn't much of an issue for Hedge if you use dynamic pruning (which @lanctot linked above). The biggest issue is the parameter tuning. There might be a way to do that well in CFR, but nobody has really nailed it yet. I did an okay job in the dynamic pruning paper but it's still not competitive with the best RM variants in large games.

Another major benefit of RM is that it doesn't involve exponentiation, which is more expensive on CPU-bound setups.

**Comment by szrlee** [comment]
Thank you for the detailed response @lanctot @noambrown !
Is the work you mentioned by @dmorrill10 this one [Bounds for Approximate Regret-Matching Algorithms](https://arxiv.org/abs/1910.01706) (Submitted on 3 Oct 2019)?

In the context of other areas, say (sample-based) repeated matrix game (I noticed this can be turned into the extensive-form game and thus using (MC)CFR), is there evidence showing (sample-based)RM performs better than (exp3)hedge?

**Comment by lanctot** [comment]
Thanks @noambrown for the follow-up. 

@szrlee, I recently read that paper and no it's not. It'll have to be a follow-up paper and/or his thesis. I might try to twist his arm to send it to the [AAAI RL in Game Workshop](http://aaai-rlg.mlanctot.info/); it follows on some work that him and Trevor Davis (another U of A student) worked on previously that was never published.

**Comment by lanctot** [comment]
Oh, realized I missed this:

> In the context of other areas, say (sample-based) repeated matrix game (I noticed this can be turned into the extensive-form game and thus using (MC)CFR), is there evidence showing (sample-based)RM performs better than (exp3)hedge?

Not in a paper that I can cite, just stories from all of us who've tried it. Maybe those results could go into the fictitious paper I've been encouraging Trevor and Dustin write. :)

**Comment by szrlee** [comment]
Nice comments! Thanks. Hope to meet you guys at Neurips this year to talk more!

**Comment by lanctot** [comment]
I will be there in December, happy to meet! Always love talking about this stuff :)
