### ISSUE TITLE
General question about python vs c++ algorithm implementations

### ISSUE THREAD

**Issue by alexminnaar** [deepmind/open_spiel#105]
Apologies if this was answered in the documentation and I missed it but it looks like there are algorithms implemented in both python and c++.  For contributors who are looking to add some algorithms is there any preference for python vs c++ implementations? Or maybe it is better to add both? Or is it a case-by-case sort of thing? Thanks.

**Comment by lanctot** [comment]
@alexminnaar , great question. It's mostly case-by-case, and depends mostly on the expected use and preferences of the contributor. I guess most machine/reinforcement learning algorithms will be in Python or Swift since they'll get the most use in those languages, whereas e.g. CFR and search could be in C++. 

We have both in many cases for two reasons: even among the team, we're split among using python or C++ depending on what we're trying to do, and we don't expect most users to mix between languages but still want them to have access to all the algorithms. 

I think the rule of thumb should be: do whatever you want! :) If you're curious about specific algorithms, air on the side of implementing it in whatever language makes more sense for its expected user base, but always feel free to check with us first if you're not sure.

**Comment by alexminnaar** [comment]
Sounds good, thanks.
