### ISSUE TITLE
About rewards() on chance node

### ISSUE THREAD

**Issue by rezunli96** [deepmind/open_spiel#1050]
Hi, I have one question about the functionality of rewards().
So suppose we have transitions (s1, a1, R1, s2), if I understand correctly, R1 = s2.rewards():
https://github.com/deepmind/open_spiel/blob/77aca74c5459121322caa079dfb6e7eb1ba075c4/open_spiel/spiel.h#L106-L109
However if s2 is a chance node, according to the following comments, s2.rewards() will be forbidden.

https://github.com/deepmind/open_spiel/blob/77aca74c5459121322caa079dfb6e7eb1ba075c4/open_spiel/spiel.h#L325-L344

So in this case, how can we get R1?
One possibility to deal with this case is to store R1 on the next non-chance node: (s1, a1, R1, s2, a_c, s3), where s3 is a non-chance node and R1 = s3.rewards().

However, what if the environment will also render rewards for the players when the chance is taking an action? For example, if the transitions are (s1, a1, R1, s2, a2, R2, s3, a3, R3...) where s2, s3 are all chance nodes, then how can we correctly get the accumulated return?

**Comment by lanctot** [comment]
Currently there is no way to get R1 separately. You have to wait until a non-chance node (say s') and get all the rewards between s1 and s'.  This what s'.rewards() would give.

> However, what if the environment will also render rewards for the players when the chance is taking an action? For example, if the transitions are (s1, a1, R1, s2, a2, R2, s3, a3, R3...) where s2, s3 are all chance nodes, then how can we correctly get the accumulated return?

Do you have an example game where this is the case? We decided for simplicity to not allow this, specifically because we could not think of an example where the algorithms would take advantage of the decomposed rewards between chance nodes (in fact, most RL algorithms would not even "see" the chance nodes, the RL environment just hands them the rewards between s1 and s4.

**Comment by lanctot** [comment]
We could revisit this choice if there is a use case being prevented by it, just let us know.
