### ISSUE TITLE
shflags error on Mac

### ISSUE THREAD

**Issue by findmyway** [deepmind/open_spiel#132]
Although the travis build runs successfully, there are some errors with the build on Mac. See https://travis-ci.org/deepmind/open_spiel/jobs/633477796#L272-L275 

I guess that is the main reason why the build on Mac hit [this branch](https://github.com/deepmind/open_spiel/blob/master/open_spiel/scripts/build_and_run_tests.sh#L125-L136), while on Ubuntu it hit [the other branch](https://github.com/deepmind/open_spiel/blob/master/open_spiel/scripts/build_and_run_tests.sh#L137-L162).

One possible solution may be https://github.com/kward/shflags/issues/13#issuecomment-404684801

**Comment by ZiggerZZ** [comment]
Do you know if this is the reason why I find folders bdist.macosx-10.7-x86_64/, lib.macosx-10.7-x86_64-3.6/ and temp.macosx-10.7-x86_64-3.6/ in open_spiel/build/?
It looks like the content of temp.macosx-10.7-x86_64-3.6 should be in the build/ directory.
Since there is no python in build/, I can not add it to my .bashrc and use the library pyspiel right now.

**Comment by findmyway** [comment]
I'm not very sure (to be honest I haven't used Mac for years 😢 ). I think you can run `build_and_run_tests.sh` step by step to figure out which step is not working as you wish.

**Comment by lanctot** [comment]
Thanks @findmyway . I'm planning to remove the dependency on shflags -- it is unnecessary.
