### ISSUE TITLE
Support vector-form CFR?

### ISSUE THREAD

**Issue by lihuiknight** [deepmind/open_spiel#145]
Dear Authors,

Does open spiel support vector cfr, that is, performing cfr on public tree?

I am running cfr_example.py on leduc_poker to test the performance of open spiel.  It seems that even for this toy game, it will need a lot of time to finish 1k iterations? I plan to evaluate one multi-agent reinforcement learning algorithm on large-scale imperfect information games, so that the running time will be very an key issue.

BTW, the default setting is simultaneous updates or alternating updates?

**Comment by lanctot** [comment]
Hi @lihuiknight,

No there is currently no public tree support in OpenSpiel, though the topic has come up several times. We want to eventually support factored observation games (public observations), which should allow vector CFR, but it is currently nobody's top priority.

Alternating updates is the default. If you want faster iterations and plan to scale to larger games, I strongly recommed using the C++ implementations rather than the python ones.

**Comment by lanctot** [comment]
Btw I noticed in `cfr_example.py` that the exploitability is computed every 10 iteratiins by default. Could the slowdown you are seeing be due to running the best response too often? (Try `print_freq = 999`)

**Comment by lihuiknight** [comment]
Although set print_freq=999, the performance is still the key limitation. I guess this issue comes from two points: (1) value-form updating; (2) written in python.

Thanks for your reply. I close this issue and  do more tests on open spiel.
