### ISSUE TITLE
documentation incorrect

### ISSUE THREAD

**Issue by Wouter1** [deepmind/open_spiel#169]
In the documentation https://www.groundai.com/project/openspiel-a-framework-for-reinforcement-learning-in-games/1 we read in several places that games are written in C++

>  Game implementations are in C++ and wrapped in Python

>   Games are written in C++

This is incorrect and may lead to people giving up on using this.

If you open python/games/tic_tac_toe.py you read what I suppose to be really correct

>Games are strongly encouraged to be written in C++ for efficiency and so tha tthey can be available from all APIs. Writing Python-only games means that they will be slow and only be accessible from Python algorithms.
> Nonetheless, there are many cases where this is desirable (or required),....

**Comment by lanctot** [comment]
It is not incorrect. 99% of the games are written in C++, and just like any higher level API one could simply choose to abide by the higher-level API only (we cannot prevent this) so we provide a single game implementation in Python for people who do not want to use C++.

**Comment by Wouter1** [comment]
@lanctot  

"Games are written in C++" reads as a REQUIREMENT. 

But it is not a requirement.
Therefore I think it's incorrect.
That 99% of the games is in C++ does not make it a requirement.

>and just like any higher level API one could simply choose to abide by the higher-level API only

There is no mentioning of a higher-level API. Yes it says games are wrapped in python but that does not override the stated requirement. 

Also I assume you can not use any other higher level API (say, java). How would you then use the agents and algorithms?

**Comment by Wouter1** [comment]
Some code suggests MujocoEnv is C++

But there is code in gym/envs/mujoco/mujoco_env.py that is pure python.

**Comment by lanctot** [comment]
"Games are written in C++" is an objectively true statement that is as correct now as when we wrote it. ;-)

Joking aside, it cannot be a requirement, even if we wanted it to be. The higher-level API I am referring to is just pyspiel: anybody could have written a game that exposes the same methods as the C++-wrapped games and the python algorithm would have no way of knowing. The same is true for any language (i.e. Julia and/or Java). The obvious downside with doing this is that then those games are only available to algorithms in those languages.

We provide the python game only because we expect it to be a common use case for people who really do not want to use C++. If we hadn't provided it, people could have done it anyway. We are not encouraging people to do this because of the downsides, but as always people are free to do whatever you want. :)

**Comment by Wouter1** [comment]
@lanctot  it's not true, the one game in python is the counter example. The crux is that most of your system will still work if you write the game in python because the rest of your system is in python anyway (if I get it correctly). It would not if I wrote a game in Java. 

Anyway I'm just pointing out this mistake, for me it's a mistake so it probably is for others. I tried my best to explain the problem but in the end it's your call.

**Comment by lanctot** [comment]
> The crux is that most of your system will still work if you write the game in python because the rest of your system is in python anyway (if I get it correctly). It would not if I wrote a game in Java.

There are several algorithms in Python, but you don't have to use Python to use OpenSpiel. There are many classical tabular and search algorithms written only in C++ (see https://github.com/deepmind/open_spiel/tree/master/open_spiel/algorithms). You can use OpenSpiel for research without ever touching the Python parts if you want.

**Comment by maayanorner** [comment]
It is probably a "noob question" - but I wonder, is there anything in OpenSpiel's architecture that makes python games slower than they would be if used without OpenSpiel? Because I do experience bad performance for my simple custom Python game, and I use a simple, custom RL algorithm without many moving parts (validated that the bottleneck is the env).

I know it's not very specific but I wonder if it might be the case because it might be better for me to just implement the same API in pure Python (some kind of overhead?).
