### ISSUE TITLE
No cuda support for NFSP algorithm

### ISSUE THREAD

**Issue by fmxFranky** [deepmind/open_spiel#177]
First of all, thanks for the repo!
I am trying to use NFSP to run some simple imperfect-information games implemented in the repo, however, I found that the networks and losses in NFSP/DQN didn't define on cuda(gpu) devices. Are there any methods to run NFSP on gpu device?
Thanks a lot~

**Comment by lanctot** [comment]
Hmm, should be done in the usual way..? You need to install tensorflow-gpu and then set the device to the GPU. 

Have you used Tensorflow with a GPU before? If not, there are many excellent resources online on how to do this. See https://www.tensorflow.org/install/gpu for installations and some tutorials, e.g. https://dzone.com/articles/using-gpu-in-tensorflow-model. 

We don't have any explicit examples for this because we didn't want to depend on tensorflow-gpu because not everyone has a GPU and we figured everyone would customize their training setup anyway. If you get it working, maybe you could add an example that uses the GPU as a demonstration, that would be great.

**Comment by fmxFranky** [comment]
thanks, maybe I have to set the device when building the graph. I see that other examples, such as AlphaZero, have provided the option of whether to build the graph on the GPU. I will add methods similar to that
