### ISSUE TITLE
PBR Oracle

### ISSUE THREAD

**Issue by oslumbers** [deepmind/open_spiel#179]
Hi,
I was wondering if there were any plans for an implementation of PBR to be released anytime soon?
Thanks!

**Comment by PaulFMMuller** [comment]
Hi again, @oslumbers !

Thanks again for the interest ! :) 
The current iteration of the code was meant to include support for RL algorithms. Unfortunately, since PBR cannot yet be used in such frameworks, we haven't made it a priority. (The paper only investigated it in Normal Form Games' settings) If using PBR interests you, though, please don't hesitate to add it (And, if you feel like it, the mElo-based random game generation algorithm included in Annex C of the paper) to OpenSpiel! :)

**Comment by oslumbers** [comment]
Hi @PaulFMMuller!

Thanks for letting me know, am doing some working on PSRO over the next few months so will let you know if I get round to implementing it :)

**Comment by lanctot** [comment]
Hi @oslumbers just checking in on this. Is it still on the road map? Any way we can help?
