### ISSUE TITLE
Support for Checkers

### ISSUE THREAD

**Issue by justinkterry** [deepmind/open_spiel#180]
Would you be willing to support checkers? I think that it's a really interesting game for RL because of how jumping impacts the action space.

**Comment by lanctot** [comment]
Yes, absolutely, I would love to have checkers in the list of games! It also played an important role in the history of AI.

We just need someone to implement it.... are you offering to? :)

**Comment by justinkterry** [comment]
What would the action space even look like for checkers? No one I'm aware of has done a serious RL implementation of it.

The action space would be unfathomably large because of jumping if it were all one action space, and the only clear way I can see to get around this would be to let an agent act again after a jump, but that seems very wierd and unlikely to be a good idea.

**Comment by elkhrt** [comment]
Having multiple moves per turn seems like the simplest solution to me. So
there would be up to four actions per piece, which is very manageable. We
could have a feature in the observation to indicate which piece is being
moved so that there's no need for the agent to have any memory. Very often
there will only be one legal continuation, and we could force-play the
moves after the first.

Edward

**Comment by lanctot** [comment]
Yes I was going to suggest exactly what @elkhrt said. 

The other thing to keep in mind: there was a lot of research done on this game (search programs like Chinook and then solving it, etc.) Might be useful to know how it was typically implemented in those programs.. maybe it was separated from the general search algorithm and handled using specific heuristics (like the doubling cube in backgammon)... but maybe they implemented it in the way we're suggesting, that would be great because it would match the "standard" way of implementing the game.

**Comment by lanctot** [comment]
Mmmm.. almost certainly this would not be the canonical way the search algorithms did it, because they could have encoded jumps  efficiently using bits in a 64-bit integer (flip every bit that corresponds to: start location, end location, and every checker that you're jumping over). That would be difficult in our case, because it would make it hard to have a hard-coded range of all valid moves. So yeah, I think Ed's original suggestion is the better way to go for RL.

**Comment by lanctot** [comment]
@justinkterry just checkin in on this. Were you intending to implement checkers? Any way that we could help?
