### ISSUE TITLE
Is there any method to accelerate cfr methods?

### ISSUE THREAD

**Issue by JialianLee** [deepmind/open_spiel#182]
I test CFR on the Leduc poker. I count the number of visited states during CFR updating process. The print_freq = 10.

On my own Mac, it costs around 200 seconds to visit 1e6 states. It seems to be slow. Is there any method that we can accelerate CFR?

Thanks~

**Comment by lanctot** [comment]
I think it's because you print_freq is so low, the time is likely being dominated by the best response computation. Try setting print_freq to 100 or 1000.

I guess you are using Python; we also have implementations in C++ that are much faster.

Also, this is vanilla CFR so it will be quite slow generally; we should really add chance sampling at some point!.. maybe I'll do that soon. If the per-iteration time cost is too high after those options, then you could try switching to outcome sampling or external sampling.

**Comment by lanctot** [comment]
Hi @JialianLee , was this resolved?

**Comment by JialianLee** [comment]
Thanks a lot! 
Large print_freq can imporve. We are considering turning to C++ implementations.
