### ISSUE TITLE
Known issues with colab

### ISSUE THREAD

**Issue by lanctot** [deepmind/open_spiel#191]
It seems that the some packages on colab servers have been upgraded (e.g. sonnet) causing some backward-compatibility issues with the Python learning algorithms.  (See some discussion here: https://github.com/deepmind/open_spiel/issues/190)

We know about it, but we're not sure when we will be able to fix this. If anybody works out what to fix, a PR would be greatly appreciated!

**Comment by lanctot** [comment]
Quick update that we are working on getting OpenSpiel to work on Ubuntu 20.04 (see https://github.com/deepmind/open_spiel/issues/166). I think those fixes will also mostly fix colab, so stay tuned!

**Comment by yarncraft** [comment]
Hello again @lanctot, I have been able to construct a _Dockerized_ OpenSpiel JupyterLab so that users can experiment with the code and write new algorithms in the popular Jupyter Notebook environment.

Thanks to Docker you can also deploy it on a larger VM without a hassle (we are doing this with a Compute Optimized Azure instance at the moment) and have an amazing development workflow.

When I have some time left I will push my changes!

![image](https://user-images.githubusercontent.com/15328198/81825695-3a2d2b00-9537-11ea-83e5-5ac4c9c762f9.png)
![image](https://user-images.githubusercontent.com/15328198/81825753-4c0ece00-9537-11ea-8730-158ece8c1167.png)

**Comment by lanctot** [comment]
This looks awesome! Thanks @yarncraft for your continued contributions :)

**Comment by sullins2** [comment]
This might not be a complete fix, but in some cases simply reverting to Tensorflow 1.x will make everything work. I have been using policy_gradients.py, for example, and currently Colab will spit out a bunch of errors. Simply run a cell with this first and it will work:

%tensorflow_version 1.x

**Comment by lanctot** [comment]
Nice, thanks @sullins2!

And, actually, small update on this: thanks to @dhennes, our Monday update will have a fix that should solve a lot of the current problems with colab, too!

**Comment by yarncraft** [comment]
_I submitted a PR that offers a good alternative:_
https://github.com/deepmind/open_spiel/pull/219
