### ISSUE TITLE
Action abstraction and information abstraction.

### ISSUE THREAD

**Issue by ravigupta2323** [deepmind/open_spiel#243]
Dear Authors, I am working on universal_poker using open_spiel (python) and was wondering if there is a standard way to add information abstraction and action abstraction to these games and then use the preexisting algorithms on the abstracted game?

If there isn't a standard way, what would be your suggestion to do this? I was currently thinking of subclassing the state class and changing the definition of the infomation_state_string  and information_state_tensor methods. Is this the best way? 

Thanks a lot for this wonderful platform and your help!

**Comment by lanctot** [comment]
Hi @ravigupta2323,

Yes, there is, but we only have action (betting) abstraction implemented currently. The abstract game is the one that gets loaded as a function of thr specified game strings (the algorithms don't even know they are playing in an abstracted game-- from their perspective it is just the game itself). See the game strings in here: https://github.com/deepmind/open_spiel/blob/master/open_spiel/canonical_game_strings.h

I assume by information abstraction you mean card abstractions? Or do you mean imperfect recall abstractions? I would guess that either of those should be easy to support in the same way (via flags in the game string). @jhtschultz @finbarrtimbers would you agree?

**Comment by jhtschultz** [comment]
Yeah should be relatively straight forward. Like you said, card & imperfect recall abstractions only require altering the algorithm's perception of the game, so I think that's just a matter of modifying InformationStateString()/Tensor() and ObservationString()/Tensor(). Betting abstractions can also affect LegalActions(), so that's something to be aware of.

Abstractions can get sophisticated, so I'd suggest separating out that logic from the string/tensor functions. It'd be nice to be able to modify the internals of the abstraction code without having to change universal_poker. Then as @lanctot suggested, configure the abstractions via flags in the game string.

Btw just discovered that Slumbot's source code is available https://github.com/ericgjackson/slumbot2019. That might be a good place to look for inspiration on how to implement the abstractions themselves.

**Comment by ravigupta2323** [comment]
Hi @lanctot @jhtschultz, thanks for the prompt response. I was currently thinking of only card abstraction with perfect recall. Also currently available betting abstractions are quite restrictive, I wanted to add a few more bet sizes.  


While I agree that adding new flags to game strings would be relatively easy. I think to keep the implementations separate we might want to do it using game transforms (game wrapper)?

By changing the game string, I would be changing the game itself. I wanted to do it in a way such that it is possible for 2 players with different abstractions to play each other (via action translation or nested subgame solving). For instance, using pre-implemented CFR with different abstractions for each player. Or using CFR for each abstraction separately and then using policies obtained to complete agents with different abstractions with each other. (I realize this can be done by loading 2 games)

As it currently stands, I am thinking of doing the following:
1. Create a game transform which takes user-defined functions for each player and returns the abstracted game. 
2. Modify methods information_state_string()/tensor() and observation_string()/tensor() to work to reflect the card abstraction.
3. Modify legal_actions() to reflect action abstraction. 
4. Modify child() and apply_action() to use action translation internally. 

What do you think? And

**Comment by lanctot** [comment]
Yeah for that kind of work (where you mix abstractions across players) then a game transform you are describing makes sense.

If you want them to play within arbitrary abstractions afterward then you could make a translation bot that takes in their learned policy and does the translations.

Thanks for the link to Slumbot @jhtschultz ! Would be neat if we could get it running in OpenSpiel!

**Comment by michalsustr** [comment]
I think the game transformation is the correct way to go about it, and I'd like to suggest two things. 

1) Maybe the transform could be more general than just Poker? It could work generally by providing a callback "translation" function, which effectively acts as an "onto" ([surjective](https://en.wikipedia.org/wiki/Surjective_function)) function for whatever object (information state / action) is being abstracted. 

2) Instead of doing both information state and action abstraction at the same time, I think it should be straightforward to do composed transformations, where you apply only one change at a time. This will allow all kinds of neat combinations of transforms, like I don't know, a combination of action abstraction and imperfect recall. You said each bot needs different abstractions, so those could be built up this way. It will also make it easier to debug, as you will be only concerned with one task at a time.  A possible downside could be slowness, but I don't think it should be too much of perfomance hit. I might be wrong though.

With regards to bots playing with different abstractions, it would be neat if the transformed games provided a way of exposing the "true state of the game", i.e. the original untransfomed state in the stack of transformations. Then you could just make the different bots make updates on the original game state while preserving their abstracted view over the game. There will be no need for bot policy translations, because that's already done by the game transform! :) What do you think, @lanctot and  @ravigupta2323 ?

**Comment by ravigupta2323** [comment]
@lanctot OpenSpiel already supports CFR+ and MCCFR, so it seems that abstractions and real-game best-response are the missing pieces of the puzzle. Although to replicate results from Slumbot, optimizing the implementations of some of the algorithms might be necessary (parallel computing and maybe using ints instead of strings? I am not sure) . 

@michalsustr I completely agree with each of your points. I was also thinking of a generic transform with a user-defined translation function. And yes, decoupling action and information abstraction seems like a more natural choice. Thanks for this suggestion! 


I'll be working on this in the coming days and will try to create PR if I get things working.

**Comment by lanctot** [comment]
@ravigupta2323 I didn't mean replicate Slumbot results I just meant getting it to run in OpenSpiel. I don't think OpenSpiel is the right code base for doing those large scale experiments, it would require optimizations specialized to poker and OpenSpiel is intended for simplicity + breadth. I am a bit surprised you want to use OpenSpiel for this kind of work (and the amount of interest in poker more generally, tbh). Aren't there existing code bases that already do these things that are better suited for poker research? Is it because you will try these abstraction ideas on other games? Contributions are very welcome, of course, just genuinely curious.

@michalsustr , sounds good! But doesn't it mean the bot would only be able to play within t0000he specific abstractions that were chosen by all the players during learning? Seems to me that you can get to a state that the bot does not know exists for arbitrary abstractions?

**Comment by ravigupta2323** [comment]
@lanctot Ohh I also wasn't thinking of replicating of Slumbot results myself I am only interested in abstractions for now. It was a general response to your comment. I wanted to use open spiel for our project because of all the preexisting algorithms and games (hidden info) to benchmark new ideas. Preexisting algos I believe are also useful as subroutines in any further work. So kudos to you guys for this :) 
My plan was to test ideas here initially and then and later move on to either specialized environments or to optimize the few algorithms in open spiel that are useful to us. I am interested in abstractions because we want to test our ideas in large poker games (And we aren't using NNs, at least initially). 

I think what we can overcome this problem by modifying child() and apply_action() to perform action translations implicitly, each player would always remain in it's specified abstracted game.

Again thanks for your help!

**Comment by lanctot** [comment]
That all sounds great! Glad we could help, and let us know if you have any more questions.

**Comment by michalsustr** [comment]
> I'll be working on this in the coming days and will try to create PR if I get things working.

I can try to add a function which returns the original untransfomed state (in the list of transformations), and update already existing game transforms accordingly. Basically we can create a [category](https://en.wikipedia.org/wiki/Category_(mathematics)) of `State`, where the untransfomed state is an [initial object](https://en.wikipedia.org/wiki/Initial_and_terminal_objects). 

> sounds good! But doesn't it mean the bot would only be able to play within the specific abstractions that were chosen by all the players during learning? Seems to me that you can get to a state that the bot does not know exists for arbitrary abstractions?

The the bot will be independent of whatever the other players are doing.

I thought a bit about how to do this for arbitrary abstractions. The following is a description how these things could work "idealistically", and then maybe we could come up with reasonable practical compromises.

I think that `Bot` should get the `Game` in it's constructor and create it's own (possibly abstracted) representation of the `State` that it can then pass to its underlying algorithm, or use it for lookup in the (possibly abstracted) policy table. In fact, `Bot` should never get `State` externally! He should always try to update the state based _only_ on its observations in the game. 

When the bot is called an `InformAction()` (and there should be also an `InformObservation()`, one could argue that he _observes_ an action, so that should be part of player observations, and therefore only `InformObservation` should exist), he can advance his abstracted state by applying the action _to the untransfomed state_. This change will then propagate right through all of the abstractions. 
When the bot is asked to `Step`, we may need to do action translation. We can clone the abstracted state, apply abstracted action and see how the underlying original state changed. Then we find the difference - the corresponding action - and return it as the translated action for the real world state. 

How I imagine it could work ideally, is that by applying the appropriate (abstracted) action to the corresponding (abstracted) state anywhere in the list of transformations, all of the (transformed) states should be able to advance forward, as they are basically just statless functions that operate on the pointer to the untransfomed state. 

For this to work, the transformations must be stateless. I'm not sure however: is statelessness in game transformations too much to ask?

**Comment by finbarrtimbers** [comment]
Sorry folks, I'm slow at checking Github.

Imperfect recall (at least one version) is supported in UniversalPoker in the observation. The observation only includes the pot size, and not the actual sequence of betting actions to get there. 

Depending on the action abstraction you want, it should be easy to implement. You can look at the code in `UniversalPokerState::LegalActions()` and in `UniversalPokerState::DoApplyAction` for an example.

**Comment by elkhrt** [comment]
I'm not entirely sure I understand the proposal for handling mismatched
abstractions. If one player thinks the only possible betsizes are 1, 2, 4
but its opponent bets 3, then there will be no direct state translation
available. Of course, approximations are possible.

**Comment by lanctot** [comment]
Hi @ravigupta2323 , just wondering if your issue has been addressed? Happy to discuss further, but the last response was one month ago. Prefer to close and re-open if/when we have more to talk about.

**Comment by ravigupta2323** [comment]
Hey, sorry for not updating. I tried to implement the game transform but I realised I didn't fully understand what to do and am caught up in exams rn. 

You can close the issue now, I'll reach out again if I need any help.

**Comment by lanctot** [comment]
Sounds good, thanks!

**Comment by zkristic** [comment]
Hi everyone. It's been almost 5 years since this question has been asked and I'm wondering if anyone has managed to implement card abstraction or port it from slumbot? I can't seem to find any examples officially or otherwise, only the ones related to betting abstraction (fc, fcpa, fullgame, etc...).

**Comment by lanctot** [comment]
Hi @zkristic, nope nobody has added any card abstractions.

As it's not a priority for us, it's something that would need to be contributed. If you add the functionality, it'd be great if you made a pull request for us to merge into the code base.

**Comment by zkristic** [comment]
Hi @lanctot, I am interested in making this contribution, however I do not have a prior experience in cpp, so it might take me some time, and it might not be the prettiest or up to the standards (but we can rely on code review to fix that). Regardless of that, I do have couple of questions for you and/or anyone else who knows open_spiel in detail. Reading this thread, I'm under impression that card abstraction would be a relatively straightforward implementation:

1. implement hand bucketing: basically, find highest ranking hole (private) and board (public) cards combination and assign a bucket to it
2. modify InformationState* to reflect changes, where * is String, Tensor, TensorShape
3. modify Observation* to reflect changes, where * is String, Tensor, TensorShape

My questions are related to the latter two. Currently, tensor shapes are calculated as

- InformationState `{num_players + 2 * total_num_cards + (2 + 1) * gameLength}`
- Observation `{2 * (num_players + total_num_cards)}`

Now, if instead of one-hot encoding entire deck twice (once for private cards and once for public cards), we will one-hot encode buckets, correct? If yes, new tensor shapes would be calculated as

- InformationState `{num_players + num_buckets + (2 + 1) * gameLength}`
- Observation `{num_players + num_buckets + num_players}` or `{2 * num_players + num_buckets}`

Thing that makes me not confident in this approach is that in worst case scenario, we are encoding vector of size 104 (full deck times two) for unabstracted game, and vector of size `num_buckets` for abstracted game. Which means, we would have to have much less than 100 buckets for it to be more optimal than unabstracted game, and with such small number of buckets strategies could be significantly impacted.

Am I missing some crucial part of Algorithm/Game/State which also requires implementation updates/changes? Do you have an idea by which factor would number of states drop for, let's say, 10 buckets? If we check `count_all_states` output for this game string:
```sh
./count_all_states --game_string "universal_poker(betting=nolimit,numPlayers=2,numRounds=2,blind=100 50,numSuits=1,numRanks=13,numHoleCards=1,numBoardCards=0 2,stack=2000 2000,bettingAbstraction=fcpa)"
Game: universal_poker(betting=nolimit,numPlayers=2,numRounds=2,blind=100 50,numSuits=1,numRanks=13,numHoleCards=1,numBoardCards=0 2,stack=2000 2000,bettingAbstraction=fcpa), num_histories: 1723034, num_terminal_histories: 1082796, num_chance_nodes: 20606, num_nonterminal_states: 31044, num_terminal_states: 1082796
```
do we expect all of these numbers to drop, or just select few like `num_nonterminal_states`?

**Comment by lanctot** [comment]
Hi @zkristic, thanks for the offer.

Sorry for the delay.. I'm a bit overloaded at the moment. There will be some delays in communication.

How about subclassing the main poker state + game and just overriding the methods that you need? That seems like the perfect use for inheritance and the cleanest way to keep all the card abstraction logic separate from the already-complex poker wrapper? The underlying game doesn't change, right-- only the observations?

**Comment by lanctot** [comment]
BTW I am not a poker expert, so I will defer the Poker questions to @jhtschultz and @Drazcmd

**Comment by jhtschultz** [comment]
Hi @zkristic, +1 to Marc's suggestion, I think subclassing is the way to go here for the sake of simplicity. Your description of how to apply bucketing sounds right to me, though I haven't really thought about this in a long time and there may be other considerations. I'd recommend reviewing the literature on poker state abstractions, finding something reproducible, and going from there. Here are a few papers worth looking at -- others might know the most important papers in this space but I'm sure you can find them with these as a starting point: https://www.cs.cmu.edu/~sandholm/BabyTartanian8.ijcai16demo.pdf,  https://poker.cs.ualberta.ca/publications/AAMAS13-abstraction.pdf, https://poker.cs.ualberta.ca/publications/2014-aamas-asymmetric-abstractions.pdf.

**Comment by lanctot** [comment]
Let me add the PhD theses of these people to the list as potential starting points:

- Michael Johanson
- Kevin Waugh
- Nolan Bard
- Neil Burch

I believe both Michaels' and Kevins' master theses also talked about it them as well.

And the local best response paper probably has a good overview of some of the abstractions that were used as well (https://arxiv.org/pdf/1612.07547).

**Comment by zkristic** [comment]
@lanctot, @jhtschultz sorry for the delayed response, I've been on vacation. After glancing over linked documentation, looks like there's only general description of how abstraction should work (reduce number of nodes from unimaginable 10^165 to more manageable 10^14 by reducing number of information states). Since I'm neither poker savvy nor math savvy, I'm not expecting those white papers to help me at all with implementing this.

That being said, I fully agree about subclassing instead of modifying current implementation. I'll start my work on it, but like I said in my previous comment, I'm sceptical about my proposed approach. Seems like 100 abstractions would have the same memory footprint as full, unabstracted, game due to one-hot encoding. In theory it should be orders of magnitude more memory efficient  compared to unabstracted game.

If anyone has any more info, especially when it comes to implementation details, please chip in your two cents, I would appreciate it.

**Comment by Drazcmd** [comment]
Not sure if anyone had mentioned Noam Brown yet, but if you're after details on using abstraction for poker purposes I'd definitely recommend his work! E.g. the paper and supplementary materials for Pluribus:

- https://www.science.org/doi/10.1126/science.aay2400
- https://www.science.org/doi/suppl/10.1126/science.aay2400/suppl_file/aay2400-brown-sm.pdf

as well as some of the talks on YouTube he's done.

For example, this section seems highly relevant:
```
Abstraction for large imperfect-information games

There are far too many decision points in no-limit Texas hold’em to reason about individually. To reduce the complexity of the game, we eliminate some actions from consideration and also bucket similar decision points together in a process called abstraction ([24](https://www.science.org/doi/10.1126/science.aay2400#core-collateral-R24), [25](https://www.science.org/doi/10.1126/science.aay2400#core-collateral-R25)). After abstraction, the bucketed decision points are treated as identical. We use two kinds of abstraction in Pluribus: action abstraction and information abstraction.
Action abstraction reduces the number of different actions the AI needs to consider. No-limit Texas hold’em normally allows any whole-dollar bet between $100 and $10,000. However, in practice there is little difference between betting $200 and betting $201. To reduce the complexity of forming a strategy, Pluribus only considers a few different bet sizes at any given decision point. The exact number of bets it considers varies between 1 and 14 depending on the situation. Although Pluribus can limit itself to only betting one of a few different sizes between $100 and $10,000, when actually playing no-limit poker, the opponents are not constrained to those few options. What happens if an opponent bets $150 while Pluribus has only been trained to consider bets of $100 or $200? Generally, Pluribus will rely on its search algorithm (described in a later section) to compute a response in real time to such “off-tree” actions.
The other form of abstraction that we use in Pluribus is information abstraction, in which decision points that are similar in terms of what information has been revealed (in poker, the player’s cards and revealed board cards) are bucketed together and treated identically ([26](https://www.science.org/doi/10.1126/science.aay2400#core-collateral-R26)–[28](https://www.science.org/doi/10.1126/science.aay2400#core-collateral-R28)). For example, a 10-high straight and a 9-high straight are distinct hands but are nevertheless strategically similar. Pluribus may bucket these hands together and treat them identically, thereby reducing the number of distinct situations for which it needs to determine a strategy. Information abstraction drastically reduces the complexity of the game, but it may wash away subtle differences that are important for superhuman performance. Therefore, during actual play against humans, Pluribus uses information abstraction only to reason about situations on future betting rounds, never the betting round that it is actually in. Information abstraction is also applied during offline self-play.
```
