### ISSUE TITLE
Question about design decision for "Qwinto" game

### ISSUE THREAD

**Issue by mpflanzer** [deepmind/open_spiel#250]
Hi all!

I'm currently trying to figure out the best way to implement the game "Qwinto". The complete rules can be found here: https://www.ultraboardgames.com/qwinto/game-rules.php

In short, it's a turn-based game. During each turn **one** player rolls one to three dice up to two times and then **all** players enter the result into an empty field in their personal score card. In the next turn the next player rolls the dice and so on.

I'm especially looking for recommendations/guidelines how to implement the fact that in the first two steps of a turn a single player is making decisions -- namely how many dice to roll and whether to roll the dice a second time -- whereas in the last step all players individually need to decide where to fill in the dice result in their score card.

I started with an implementation of a simultaneous move game. For all but the "current" player (the one who rolls the dice) I return an invalid action for the first two steps of the turn. For the last step all players get actions assigned depending on the state of their score card.
Does that make sense or is there a better alternative? I was thinking about converting it into a sequential move game in which the `CurrentPlayer()` is staying the same during the first to steps and only when the dice result is handled _every_ player is considered.
I noticed that sequential games seem to have better support in terms of algorithm (though I haven't yet looked at many). That's why I'm currently leaning towards converting the game type.

Also, as you might have noticed already, there is a slight confusion about the term "turn". In the game description each turn consists of multiple steps. But, correct me if I'm wrong, that is not possible in ``open_spiel``. During each iteration, i.e. checking for termination, and getting and applying actions, only one decision can be made. So in my current implementation each step is represented as an iteration.
Is there any prior or assumption what should be done/how the state should change during one of those iteration? For instance, Qwinto can only ever terminate at the end of a turn (step 3, after the players have filled in the cards) but not after either of the first to steps in a turn. So with my current implementation termination is checked too often. Not an issue in itself but makes me wonder if my design decision is good or if there is a better alternative.

Suggestions and recommendation are welcome. Let me know if any of the points above is not clear and I'll try to explain it better.

**Comment by elkhrt** [comment]
I think most natural would be to implement the game with a combination of
single-player turns and simultaneous move turns. We don't by currently have
an example of that, but it should hopefully be obvious how to do it.

You're right that most of our algorithms work only on non-simultaneous
games, but there is a wrapper to convert a simultaneous game to a
sequential one, so this is not a problem in practice.

You're quite right that a turn is a single decision. I wouldn't worry about
the termination check. It is presumably very fast for the cases which
cannot be terminal.

Ed

**Comment by michalsustr** [comment]
> I think most natural would be to implement the game with a combination of single-player turns and simultaneous move turns.

> For all but the "current" player (the one who rolls the dice) I return an invalid action for the first two steps of the turn.

I think what you chose to do is very reasonable. In fact, I'd like to argue that we should have a special `kNoOpAction` besides the `kInvalidAction` you've used, because this "action padding" is in fact necessary in [FOGs](https://arxiv.org/pdf/1906.11110.pdf) -- players take joint (simultaneous) actions, and those who are not "acting" just have these no-op actions.

@lanctot do you think we could have something like following?
```
// Constant representing an invalid action.
inline constexpr Action kInvalidAction = -1;
// Constant representing a "no-op" filling action in simultaneous-turn games, 
// for turns where some players are not acting. For these players we need 
// to "pad" their actions.
inline constexpr Action kNoOpAction = -2;
```
Are negative `Action` forbidden, do some games use them?

**Comment by mpflanzer** [comment]
> I think most natural would be to implement the game with a combination of single-player turns and simultaneous move turns.

I converted my initial approach with only simultaneous turns and "noop"/invalid actions into a mixture of single-player and all -player turns. See this commit: https://github.com/deepmind/open_spiel/commit/9c85c7ec0e357243348ae66a84e9c1bc69834d70
To make this work I had to adapt the simultaneous move game like this: https://github.com/deepmind/open_spiel/commit/78cf523a51065840bf7a3bba65bf37cf574a475a So far that seems to work just fine. Though I'm not sure if that change might have some unwanted side effects.

`CurrentPlayer()` now returns `kChancePlayerId` to simulate rolling the dice, `kSimultaneousPlayerId` for turns in which all players have to act (i.e. writing down the dice result), and the current player id for all turns in which only one player is making decisions. @lanctot, is that what you had in mind?

For reference, here is the full implementation: https://github.com/mpflanzer/open_spiel/tree/feature/qwinto

**Comment by elkhrt** [comment]
Thanks Moritz - that looks good to me; could you fix the now-outdated
comment in simultaneous_move_game.h
<https://github.com/deepmind/open_spiel/commit/78cf523a51065840bf7a3bba65bf37cf574a475a#diff-b8f76afdaf8c1b8eb720427ef6fcd2b8>
as
well?

Michal - it seems a pretty simple extension of the FOG formalism to allow
single-player turns, but if we don't want to allow for that it would
perhaps be simpler to write a wrapper that converts a turn-based game into
the simultaneous form. That would avoid having to change all the existing
games too.

**Comment by lanctot** [comment]
Hi Moritz, sorry for chiming in late. I think the way you have it now makes sense. 

Michal, what you are suggesting makes sense if every step was simultaneous, but I don't see why we should force that in cases like this. Seems more natural to just have the game implemented as a mixture of turn-based and simultaneous nodes.

As Ed implied, I think the turn based simultaneous game wrapper should already work out of the nox, but we don't have any games in this category. If you haven't already could you try running a simulation test under the wrapper to verify?

**Comment by mpflanzer** [comment]
No worries, thanks for the suggestions. Did you have any specific test in mind? I quickly adapted the `mcts.py` example to load the game via `load_game_as_turn_based`. That is running without issues -- tough the bot is not exactly making the smartest decisions. :wink: Looks like I should now spend some time to figure out which algorithm to select.

**Comment by lanctot** [comment]
Yeah I meant our standard simulation tests (uniform random simulations that test a bunch of properties).

Should be a one-line test that looks like this: https://github.com/deepmind/open_spiel/blob/63ede7dee69c79510ff99dac99c68b8e368f6a9a/open_spiel/games/goofspiel_test.cc#L31

Except you replace the game string by the one I gave about (or you could use `LoadGameAsTurnBased` if you want). So instead of `LoadGame("qwinto")` you would do `LoadGame(`turn_based_simultaneous_game(game=qwinto)`. 

If MCTS runs on the game then chances are this already works, but it'd still be a good sanity check to have in your basic tests.

And... yes, MCTS with random playouts is quite vanilla for an AI :) In a larger game, you need many playouts before this starts looking anything resembling "somewhat ok". You can always add a custom evaluator that does more informed playouts and/or mixes with minimax search (still one of my favorites in this space is [implicit minimax backups](https://arxiv.org/abs/1406.0486) but we don't have it implemented. Would love to have it though.) But really depends what you are trying to do, e.g. more RL or more game-tree search using heuristics. Glad to discuss it and offer advice, but curious what your goals are before I say more.

**Comment by michalsustr** [comment]
Enabling single player turns in simultaneous games with #255 makes sense. I was just wondering whether it would not be confusing for new-comers, since now you can have a sequential and "simultaneous-turn" games which are exactly equal. Which one should you use? Simultaneous seems more powerful, because there is a transformation to sequential (so you don't lose anything), but there is no transformation the other way around.

I would still like to pitch the `kNoOpAction`: imagine you have a game with 10 players, and only a random subset of them gets to act. Then the remaining players have to "fiddle their thumbs" by "playing" no-op. Sure, the game author can handle this internally for the game, but providing a general way to do so might be more useful / idiomatic for future use.

**Comment by lanctot** [comment]
> I would still like to pitch the `kNoOpAction`: imagine you have a game with 10 players, and only a random subset of them gets to act. Then the remaining players have to "fiddle their thumbs" by "playing" no-op. Sure, the game author can handle this internally for the game, but providing a general way to do so might be more useful / idiomatic for future use.

Oh yes, I agree with that, makes complete sense. You're advocating for supporting games in which a simultaneous node leads to a subset of players acting simultaneously, and the players outside that subset **must** return `kNoOpAction`. 

But I think this is a separate topic, right. As in, it's independent of the choice made by @mpflanzer, right? Qwinto does not have situations like this, does it? But anyway I'm on board generally.

**Comment by elkhrt** [comment]
Continuing with the side discussion (sorry for spamming your thread Moritz!)

*Simultaneous seems more powerful, because there is a transformation to
sequential (so you don't lose anything), but there is no transformation the
other way around.*


It would be simple to write such a transformation (from sequential to
simultaneous) - perhaps we should do so if there are algorithms for which
it would be useful.

**Comment by elkhrt** [comment]
To the extent that this is in the code at all, we currently use
kInvalidAction for the padding,

https://github.com/deepmind/open_spiel/blob/2859b4c309a88ac10ec07d00cee25828682f9522/open_spiel/simultaneous_move_game.cc#L27-L44

https://github.com/deepmind/open_spiel/blob/0530df0397a35e155ea7ad0f09249eb62ab124ee/open_spiel/spiel.h#L607-L608

kNoOpAction would be a reasonable alternative if you think it would be
clearer.

**Comment by mpflanzer** [comment]
> Yeah I meant our standard simulation tests (uniform random simulations that test a bunch of properties).

Ah, yes, that runs without issues as well.

> But I think this is a separate topic, right. As in, it's independent of the choice made by @mpflanzer, right? Qwinto does not have situations like this, does it? But anyway I'm on board generally.

Correct, For Qwinto it's always a single player for the first to steps and then all players in the last step that have to make decisions. (Though in the last step a player might decide to do nothing).

> kNoOpAction would be a reasonable alternative if you think it would be
clearer.

Having a `kNoOpAction` makes the intention clearer I would say. But the difference seem very subtle. It would definitely allow for better checks whether an action was submitted at all. Actions could be initialized with `kInvalidAction` and a game would return `kNoOpAction` for each player who is not allowed to participate in the current turn.

> Glad to discuss it and offer advice, but curious what your goals are before I say more.

Thank you for the suggestions already. The goal is to figure out if my brother can be beaten in this game. :wink: I really just wanted to play around a bit and see if the computer would choose a similar strategy for filling in the score card as a human player does. Coming up with a good heuristic is going to be difficult without putting in a lot of prior knowledge already. The final score can still change a lot in the last few rounds (depending on your luck). I would definitely be interested to explore RL algorithms.

**Comment by lanctot** [comment]
Hi @mpflanzer , do you still have any questions about implementation? If not, shall we close this for now? (Feel free to re-open if you have more questions).
