### ISSUE TITLE
Ubuntu 20.04 Docker container

### ISSUE THREAD

**Issue by lanctot** [deepmind/open_spiel#295]
Hi @yarncraft, we now support Ubuntu 20.04. Would you like to add it back to the Dockerfile and run the tests to ensure that it works?

**Comment by lanctot** [comment]
@yarncraft what do you think?

**Comment by yarncraft** [comment]
Hello Lanctot, sorry for the late reply, had a busy week. I will submit a PR with the updated OS tomorrow!

**Comment by yarncraft** [comment]
https://github.com/deepmind/open_spiel/blob/6172b9a72bd5d08dd5bfddbe0a0847b31cfb4ecf/open_spiel/scripts/install.sh#L206

I have tried to run it but I have the following remark: 
The installation of the dependencies on line 206 of _install.sh_ should support container (headless) creation through `apt-get -y install`. Since, _in principle_, no user interaction is expected when pulling container images. The installation of tzdata in particular gives rise to a problem, but I am trying to fix it through the following proposed solution: https://serverfault.com/questions/949991/how-to-install-tzdata-on-a-ubuntu-docker-image

**Comment by lanctot** [comment]
Hi @yarncraft sorry for the delayed reply! Yes, absolutely, we should just add the `-y` at that spot, I agree.

**Comment by lanctot** [comment]
Fixed by https://github.com/deepmind/open_spiel/commit/ddce79d1988370ee0b358ddbf03bc3811c8802d7
