### ISSUE TITLE
[Question] REGISTER_SPIEL_GAME and GameType in parameterised games

### ISSUE THREAD

**Issue by DennisSoemers** [deepmind/open_spiel#298]
What should I do about `REGISTER_SPIEL_GAME` and `GameType` in parameterised games, where different `GameParameter` selections should lead to different values for some of the `GameType` variables?

For context: I'm thinking here of (finally) continuing the [Ludii general games wrapper](https://github.com/deepmind/open_spiel/issues/39). Ludii has hundreds of games implemented. My thinking was, OpenSpiel would probably just have a single "LudiiGame" implementation, with at least one mandatory `GameParameter` of type string that would contain the name of the specific game to be loaded from Ludii (e.g. `Tic-Tac-Toe.lud` to load Ludii's version of Tic-Tac-Toe). Many games in Ludii themselves also have parameters to tweak aspects like board size, player number, sometimes rules, etc., which could all be further customised through additional `GameParameters` from OpenSpiel... but I'm mainly worried just about the first and biggest one here; the game name.

If we only have a single LudiiGame, I assume that I can only register it once through `REGISTER_SPIEL_GAME`, and provide only one `GameType`. Here I could specify only a single `GameType::Dynamics` value, a single `GameType::ChanceMode` value, etc. So which should I pick here? I assume the most "general" ones, which would mean that OpenSpiel thinks that even Ludii's implementation of Tic-Tac-Toe is a stochastic, simultaneous-move game with imperfect information for 16 players. How bad would this be? Would there be a better solution?

**Comment by lanctot** [comment]
Hi Dennis, 

Yes I'd prefer a single `LudiiGame` game and single game type. I would recommend setting the defaults parameter values to something that makes sense for a specific game (e.g. TicTacToe) and just putting a comment that these values will depend on the game and be changed when the game instance is created. You can also go the route of having non-mandatory parameter values without any defaults set (we have a few examples of that; I just fixed a bug related to it: Go is one instance). I would not choose the most general ones because some of them don't have subsumption relationships. 

Then the recommended thing in your case would be to assemble the actual GameType (depending on the chosen game) in the `LudiiGame` constructor, and store it in `game_type_`, that way `LudiiGame::GetType()` returns the one appropriate structure for the specific game that was instantiated.
