### ISSUE TITLE
RuntimeError: Unknown parameter players

### ISSUE THREAD

**Issue by SixTRaps** [deepmind/open_spiel#34]
Hello,

I tried to use example.py to play a tic_tac_toe game using command `python3 example.py --players=1`. Here's the error I ran into:
`Traceback (most recent call last):
      File "example.py", line 111, in <module>
          app.run(main)
      File "/open_spiel/venv/lib/python3.7/site-packages/absl/app.py", line 299, in run
          _run_main(main, args)
      File "/open_spiel/venv/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
          sys.exit(main(argv))
      File "example.py", line 46, in main
          {"players": pyspiel.GameParameter(FLAGS,players)})
RuntimeError: Unknown parameter players`
The example.py works well if I do not pass any parameter to it. Could anyone tells me how to solve this problem? Thanks!

**Comment by lanctot** [comment]
The example.py file simulates a game using random players. The --players parameter specifies the number of players in a parametrized game that supports different numbers of players (e.g. kuhn_poker or pig). Tic-Tac-Toe does not support the players parameter since it is a strictly two-player game.

From the wording in your comment it sounds like you want to play a game. In that case you should run the human_vs_ŕandom.py example, which is possible thanks to the contribution on @juliendehos here: https://github.com/deepmind/open_spiel/pull/12

**Comment by SixTRaps** [comment]
Thank you so much!
