### ISSUE TITLE
Vanilla CFR average policy question

### ISSUE THREAD

**Issue by inejc** [deepmind/open_spiel#387]
Hope asking this via issue is ok as it is only very implicitly related to the implementation in OpenSpiel. I'm reading [1], [2] and [3] and can't seem to find a good explanation about the definition for the average policy. Particularly, I'm wondering why the averate strategy (equation (4) in [1] or equation (3) in [2]) is weighted by player's reach probability at timestamp `t` (and I see that OpenSpiel implementation does the same)? I realize there's a theorem right after the equations stating the connection betwen the average sigma at `T` and the equilibrium for zero-sum games but there's no proof for theorem 2 even in appendix of [1].

Is there an intuitive explanation for including reach probabilities? Why wouldn't the cumulative policy simply be the sum of all sigmas over all time steps for a particular action? I'm sure I'm missing something obvious so hopefully this isn't too silly of a question.

 ### References
- [1] [Zinkevich et al., Regret Minimization in Games with Incomplete Information](http://papers.nips.cc/paper/3306-regret-minimization-in-games-with-incomplete-information.pdf)
- [2] [Lanctot et al., Monte Carlo Sampling for Regret Minimization in Extensive Games](http://papers.nips.cc/paper/3713-monte-carlo-sampling-for-regret-minimization-in-extensive-games.pdf)
- [3] [Neller et al., An Introduction to Counterfactual Regret Minimization](http://cs.gettysburg.edu/~tneller/modelai/2013/cfr/cfr.pdf)

**Comment by gabrfarina** [comment]
That formula corresponds to computing the average of the *sequence-form* strategies. 

I think the best way to think about the whole process is like this: a Nash equilibrium is a bilinear saddle point problem in the sequence form representation, that is, it can be written as the optimization problem

```
min_{x \in Q1} max_{y \in Q2} x^T A y
```

where `Q1` is the set of sequence form strategies for Player 1, `Q2` is the set of sequence form strategies for Player 2, and `A` is a sparse payoff matrix.

Now, it turns out that any time you have a bilinear saddle point, if you can build regret minimizers `R1`, `R2` for the domains of the min and max (in this case, the sequence form strategy spaces `Q1` and `Q2`), and you let them play against each other, the average strategies that they produce converge the the the solution of the saddle point problem.

You can think of CFR as a regret minimizer for the set of sequence form strategy of a player. Hence, if both players play according to the CFR regret minimizer, their average sequence form stategy converges to a Nash equilibrium. It is crucial though that you average *in sequence form*. 

The formula with the reaches that you see in those papers is simply taking a *behavioral strategy*, converting it to sequence form (by multiplying by the reaches), then averaging in *sequence form*, and finally going back to behavioral representation by dividing by the parent reach of the average sequence form strategy just computed. All in one compact formula.

**Comment by inejc** [comment]
Thanks @gabrfarina! I need to do some reading in order to better understand why the sequence form is pivotal. Do you have any suggestions for the material? [Stengel](https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/69313/1/eth-3346-01.pdf) seems relevant.

**Comment by michalsustr** [comment]
@inejc there is a simple example explaining the reaches, [slide 33](https://cw.fel.cvut.cz/b182/_media/courses/xep36agt/agt_learning3_2019.pdf) (from the course about [algorithmic game theory](https://cw.fel.cvut.cz/b182/courses/xep36agt/start)). You want to ensure that unreachable parts of the game (right action and then right subtree) do not affect the computation of the average strategy.

**Comment by inejc** [comment]
I believe I have enough resources to continue the studies. Thank you both.
