### ISSUE TITLE
Actions are broken for `fullgame` abstraction in `HunlGameString`.

### ISSUE THREAD

**Issue by finbarrtimbers** [deepmind/open_spiel#391]
In UniversalPokerGame, there are a bunch of problems with the action encoding. We've hardcoded the assumption that the bet size is a multiple of the big blind, which is wrong. As such, we've disabled it currently.

There's a stub implementation right now that uses `std::iota`; however, it doesn't work, as it will suggest illegal actions that cause the underlying ACPC game to fail.

**Comment by jhtschultz** [comment]
Just saw this…I added the “fullgame” action encoding (prior to that the only available options were FC and FCPA). Hard coding bet sizes as multiples of the big blind was a silly assumption on my part, but fixing it only requires a small modification. I’ve already got it working and will submit a PR once I finish redoing some of the tests.

Aside from the incorrect assumption, did you find any other issues with the full game action encoding?

**Comment by jhtschultz** [comment]
Btw I didn’t design the overall betting abstraction, that was already in place. When adding the full game action encoding I tried to modify as little as possible. I noted at the time that it might be worth rethinking the design, and the topic has come up since (https://github.com/deepmind/open_spiel/issues/243). It would be nice to have a more general action abstraction mechanism, but it might be superfluous unless there’s a clear use case.

**Comment by finbarrtimbers** [comment]
Yes- I did most of the betting abstraction work, and it’s not great. If you
have any interest in coming up with a better one, please do.

Also- I meant to tag you in the original post on the issue- sorry for not
doing so.
