### ISSUE TITLE
Parallelizing algorithms

### ISSUE THREAD

**Issue by sutokari** [deepmind/open_spiel#424]
Is there currently any way to parallelize algorithms such as MCCFR? Currently I run into race conditions if I try to run, for example, the OutcomeSamplingMCCFRSolver RunIterations function from several threads, but I don't know if I'm missing a way to do this currently or if multi threaded support is not implemented yet.

**Comment by lanctot** [comment]
Hi @sutokari , I assume you mean the C++ imllementation but the response is also valid for python.

None of our algorithms have support for parallelism out of the box, but should not be too hard to do with the appropriate locking of table entries across threads. If you do it, there should be a Game object per thread because the states hold a backpointer to the game that created them.

We have no plans to extend the current implementations to support parallelism, since they are meant to be behinner-friendly reference implementations and concurrency adds a fair bit of complexity. 

However, we would welcome separate threaded implementations as contributions if you are so inclined!
