### ISSUE TITLE
private / public observations

### ISSUE THREAD

**Issue by StochasticEntropy** [deepmind/open_spiel#435]
Is there a way or already planned development that makes it possible to distinguish between private and public information in games, as outlined, e.g., in https://arxiv.org/abs/1906.11110 ?

An even more fine-grained model would be ideal for a game like Hanabi, where there is partially shared, but not completely public, information.

**Comment by janrvdolf** [comment]
I believe @michalsustr is working on this.

**Comment by michalsustr** [comment]
Yes there is! Check out `observer.h`, it is implemented by games like Kuhn/Leduc Poker and Goofspiel. Also I made a visualization tool for the observations called [SpielViz](https://github.com/michalsustr/spielviz).

I think an implementation of Observer for Hanabi would be welcome, tagging @elkhrt since he might be interested.

**Comment by StochasticEntropy** [comment]
In Hanabi an Observer knows more than the players, I'd be happy to collaborate in designing a good model to describe the situation information theoretically correctly.

**Comment by lanctot** [comment]
I believe this to be resolved? So closing for now. Please re-open if necessary.
