### ISSUE TITLE
Bots API - information state instead of state

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#44]
The API currently has a method 
```
std::pair<ActionsAndProbs, Action> Step(const State& state);
```
I believe this should be rather 
```
std::pair<ActionsAndProbs, Action> Step(const std::string& informationState);
```
as the bots should not get access to current state of the world, but only to their possible perception of it. 

The current API also allows bots to "cheat", to see where they are **exactly** in the game, or to ask for observations of their opponent.

I understand changing this has some drawbacks - for example in perfect information (PI) games it's unnecessary (as num. of histories in information state is always 1) and it would require the authors somehow derive what state they are in. For such games, a workaround could be to derive all the actions from information state string -- player can always know his actions, and opponent's actions are received player's observations, since they are public in perfect info games. There can be a helper function for that in PI games. 

In imp. info games this derivation is a **crucial component** of the algorithms themselves, as they have to "figure out" what could have happened in the game so that they've received such observations.

**Comment by lanctot** [comment]
I understand the concern, but the bots need more that just their information set string. They need to, e.g. be able to query the state for legal moves, which is currently only possible from the state. The agent might be using a neural net, in which case it would need to query the state to get its information set or observation vectors. 

Of course this means the agents can cheat, but it's the responsibility of the algorithm designers or experimenters to decide whether that's ok and report truthfully, not the API to force the restriction on them. And there are legitimate use cases for wanting the ability to have cheating agents: for example, to compute bounds on values if given all the information, etc. 

If you're in a competition scenario where this would need to be enforced, it would be easy to develop a different API that only took the partial views, and that is something the competition organizers could implement separately (and we could add it to the code base); but that would be a small portion of the use cases for bots, I think, since the intention is to mostly use OpenSpiel for research and if so we can trust that the bots are being used in the way they are being reported.

**Comment by michalsustr** [comment]
I agree with what you wrote. Maybe I wanted to emphasize that II algorithms should not work with supplied State directly, but get the infoset check that they indeed have some associated state to this infoset and only then use the supplied state or the associated state. Maybe it could be mentioned in the comment.

**Comment by lanctot** [comment]
Yeah makes sense. This is not ideal. In the [Hanabi Learning Environment](https://github.com/deepmind/hanabi-learning-environment), Neil implemented the notion of a "view" (the HanabiObservation) and the agents only got access to this view into the state (which included all the information necessary as viewable from that agents, legal moves, cards, hints, etc. but *not* the hidden information they were not allowed to see). 

I like this compromise, so if it can be done in a general way, that would be the best thing to send to the bots (and if people want to have cheating bots they can still do that too using the current bots code).
