### ISSUE TITLE
Suggestion: Player instead of int

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#46]
For similar reasons why there is `typedef int64_t Action` I'd like to suggest to use `typedef int Player` as well.

**Comment by lanctot** [comment]
We actually already have it as an enum (which makes it compatible with int): https://github.com/deepmind/open_spiel/blob/626c762e7811ba0f9e2c6a45aaf6f9436aaafae6/open_spiel/spiel.h#L36

.... but's not consistently used across the code base. It probably should be; at least some of the core API functions should use it instead of int. It's a rather big change to make, though. I'll bring it up with the other team members to see what they think, but overall I think this is a good idea.

**Comment by locked-deepmind** [comment]
Yes, the type exists, but its barely used. I agree it would make things clearer to use it more consistently - PRs welcome!
