### ISSUE TITLE
Good practices for exposing state info via tensors

### ISSUE THREAD

**Issue by inejc** [deepmind/open_spiel#463]
Hi, I'm interested in implementing the `InformationStateTensor` function for the Tarok game but I think it would also be useful to have general recommendations for info state/observation tensors written down somewhere to also benefit others.

I see three possible approaches for the specific task above: (1) one-hot encode all the stages of the game, (2) have a dense representation of the info state, and (3) a combination of the two. It seems to me that (2) would result in faster convergence but it also seems implausible as the dimensionality would explode pretty quickly so I'm leaning more towards the dense, e.g.:

```python
# there are max 17 rounds of the bidding stage, a (17,) vector where elements are action IDs can encode that
# no actions
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
# first action 4
[4, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
# second action 0
[4, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
...
```

Do you have any suggestions for the encoding? Is my intuition above the dense representation correct (it's less expressive in a way)? How many dimensions are too many if I were to choose dummy encoding (I realize this is game/algorithm dependent, is there a rule of thumb suggestion that you have observed in the past)?

**Comment by lanctot** [comment]
> Hi, I'm interested in implementing the `InformationStateTensor` function for the Tarok game but I think it would also be useful to have general recommendations for info state/observation tensors written down somewhere to also benefit others.

I agree, we should have this. 

I am tagging @elkhrt who worked on the [recent paper on Bridge](https://arxiv.org/abs/2011.14124).Also @michalsustr brought this up recently, for a game like Dark Chess, it's not obvious. 

My take: I think the larger/longer the game gets, the more important it will be to use recurrent networks based on incremental ObservationTensors rather than encoding the entire information state in the tensor. For a game like Tarok, this might be inevitable... unless you start exposing your own specific features that encode the current relevant parts of the history (as is done in e.g. Hanabi)-- I think this is what you mean by "dense" infoset? I think this is a good option if you want to avoid the added complexity of recurrent networks.

**Comment by inejc** [comment]
Thanks for the suggestions, I want to avoid using RNNs on ObservationTensors for now. By "dense" I mean simply using action IDs to encode the history and my concern is that by doing that, an artificial, unrealistic distance between actions is induced, i.e. why would the distance between action 0 and action 1 be different than between action 0 and action 4.

I will try to alleviate that to some degree with only parts of the history one-hot-encoded and other parts dense. I don't think encoding the full history should be too much of a problem as visible history for a single player Is at most ~80 actions with the dense representation.

**Comment by lanctot** [comment]
Oops, yes, I agree. That sounds good but also I encourage you to also try some game specific features just to help if the learning problem ends up bein too harf. For a complex game it might require siginficant computational resources to get strong play doing it all from scratch.
