### ISSUE TITLE
calculate exploitability of an perfect information game

### ISSUE THREAD

**Issue by dylanqyuan** [deepmind/open_spiel#464]
Thanks for your attention!
 As far as I know, the application scope of exploitability in this code was limited to imperfect information game, is there any solution to calculate the exploitability of an perfect information game?

**Comment by lanctot** [comment]
Hi @dylanqyuan , we used to have some tests using Tic-Tac-Toe but they appear to be gone now. You are correct, though, it was designed for imperfect information games. Currently the best way to do a best response in perfect information games is modify value_iteration so that one player's policy is fixed.  You can also run q-learning against the fixed policy (in Python).

There is a different way to implement the best response that involves building an MDP based on the other player's fixed policies, and solving that MDP (using e.g. value iteration). This would have the benefit of supporting perfect information games **and** imperfect recall games out of the box. I might add this at some point, but I am not sure when. If you'd be interested in implementing it yourself, I can go in a bit more detail.

**Comment by michalsustr** [comment]
You can use exploitability computation also in perfect information games as long as the zero-sum rewards are given only in terminal states. Perfect information games are just a subset of imperfect information games.

**Comment by lanctot** [comment]
Yeah it might work as is but since we removed the Tic Tac Toe tests my guess is it doesn't.

If it does, it will be super inefficient. It depends heavily on perfect recall, so the information sets are defined by action sequences, rather than their more appropriate Markov state, making the games exponentially larger. It also means there is currently no way to get the exploitability of a tabular policy expressed as a map from Markovian states.

So it might work, but it if it does, it will be quite awkward to use.

**Comment by dylanqyuan** [comment]
Thank you guys for replying. These answers are very enlightening to me！ @lanctot @michalsustr

**Comment by lanctot** [comment]
Alright I finally got around to implementing this. It should be included in the next github sync.
