### ISSUE TITLE
`kStandard` strategy averaging incorrect in `ExternalSamplingMCCFRSolver`

### ISSUE THREAD

**Issue by dmorrill10** [deepmind/open_spiel#47]
https://github.com/deepmind/open_spiel/blob/ee3b6d906e982e3e62b11bf239a98340b172b9a8/open_spiel/algorithms/external_sampling_mccfr.cc#L108

The behavioral policy is being added to the cumulative policy when the player's sequence probability (the probability that the player plays to the current information state and plays action `aidx`) should be added instead. The probability that the node was sampled will also have to be taken into account by dividing by that probability.

It doesn't look like there's a trivial fix for this because the reach and sampling probabilities aren't being passed down the tree, but adding and keeping track of these values would make the fix easy.

**Comment by lanctot** [comment]
The sequence probs cancel when you do regret updates on the opponent nodes in 2-player games, leaving only the policy probability for the (infostate, action pair) and most (all?) pseudo-code thst I know presents it this way, which is why I called it standard.

I guess you are referring to the (n>2) case? I kept it as is to reflect what Noam did in Pluribus, and that's why I provided the kFull average type to do it correctly (also explained in the header comments).

Make sense?

**Comment by dmorrill10** [comment]
Thanks, @lanctot, you're right. Sorry about that. I forgot that the weighting canceled with the sampling probability and that the chance probabilities can be ignored since they're constant. When there are more than two players, since that extra player's policy might be changing, I think you should be dividing by the probability that player sampled the actions leading to the information state, no? This is a different issue from the one pointed out in the header.

**Comment by lanctot** [comment]
Yes, true, that's also broken. We should add that to the comments in the header as well and maybe kStandard is not a good word choice (maybe kSimple is better). 

I also should have mention the matching to Pluribus in the n-player case for that averaging type.

Really the only "right" one is kFull. In my chats with Rich Gibson he told me that is what he always did.

I put standard/simple because Noam said it worked fine/better and in the few quick tests I ran it seemed to be better than full.

Feel like submitting a PR? If not I will make these changes.

**Comment by dmorrill10** [comment]
You could maybe call it kPluribus and later a player sampling probability fixed version could be added kStochastic. But kSimple is fine too.

Okay, that makes sense, thanks.

You can go ahead and make the changes, thanks.
