### ISSUE TITLE
Game of Amazons contribution

### ISSUE THREAD

**Issue by selfsim** [deepmind/open_spiel#483]
Hi openspiel team,
I am an undergraduate student interested in intelligence and RL. I am planning on training various RL agents on my implementation of the "Game of Amazons", a close relative of Chess. Is this game currently in development at openspiel? If not, would you be interested in my contribution? 
Cheers

**Comment by michalsustr** [comment]
Hello @selfsim, Game of Amazons would be very appreciated! This game is not yet implemented. Do you want to do it in C++? You can take a look at the documentation where the steps are described. Feel free to post an issue if you run into problems. You may also find an inspiration in how the games for chess / go are implemented, these games have a more advanced implementation to make them fast. This could be useful for example for the [simple Amazons endgames](https://en.wikipedia.org/wiki/Game_of_the_Amazons), I think there is something similar in Go evaluation of the board, so that the game does not have to played until the last possible move. The puzzles are NP-hard according to [this paper](https://skatgame.net/mburo/ps/amaend.pdf) (referenced from Wikipedia), but from skimming the paper I think you need much bigger boards than 10x10 to run into computational issues.

**Comment by lanctot** [comment]
@selfsim it's not currently under development and would make a great contribution!

**Comment by selfsim** [comment]
Hello @lanctot @michalsustr,
so far I've been able to load my game and write a driver program which plays the game randomly.
Currently I am testing my c++ implementation with your testing harness. My implementation fails some tests and I am trying to debug it.
I've copied a sample test in /open_spiel/games as per the docs and within my test I try to run RandomSimTest, but am getting a segfault.
Could you please provide me with a sample workflow of how I can compile my test with the -g flag in order to use gdb?
I am a newb at cmake, c++, but looking around I didn't see a way to switch from release to debug.
Any help and advice concerning debugging optimization is appreciated.

Thanks!

**Comment by lanctot** [comment]
Hi @selfsim , yes you can use `export BUILD_TYPE="Debug"` to build in debug mode, which will compile with `-g -Og`. See here: https://github.com/deepmind/open_spiel/blob/a961d89273b6ae93e47755cfe3adb54ecb880966/open_spiel/CMakeLists.txt#L30

Also.. if all else fails, don't hesitate to submit a pull request... even if the game is crashing and failing tests. There's a lot of people who might be able to help you with the C++ part and basic API, and you can use it to ask questions about where the test is failing in the basic tests.

**Comment by selfsim** [comment]
Hi @lanctot thank you for the info. I have created a PR.

**Comment by lanctot** [comment]
Here is the PR: https://github.com/deepmind/open_spiel/pull/537

Thanks @selfsim !
