### ISSUE TITLE
How to interpret return value of exploitability.nash_conv()?

### ISSUE THREAD

**Issue by VitamintK** [deepmind/open_spiel#486]
A quick question that's been confounding me: how do I interpret the `player_improvements` returned by `nash_conv` in [exploitability.py](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/algorithms/exploitability.py)?

From the OpenSpiel paper: "NashConv [represents] in total, how much each player gains by deviating to their best response (unilaterally)".

However, in my testing, I've sometimes gotten negative values for one or both players in `player_improvements`, e.g. `[-0.01648912 -0.00547954]`.  Am I doing something wrong (very possible, since I'm using a custom game written in python), or is this an expected outcome?

(Secondary question: is there a better place to ask for help than here in github issues?)

**Comment by lanctot** [comment]
Hi @VitamintK, 

This is the right/only place to ask these questions.

Each player improvement (sometimes called deviation incentive) \delta_i for player i is how much a player gains by switching to their best response assuming all other players stay fixed. So these values cannot be negative, for any policy pi, for all i,  \delta_i(\pi) >= 0. 

In the C++ implementation, we even have a check to ensure this, see here: https://github.com/deepmind/open_spiel/blob/244d1b55eb3f9de2ab4a0e06341ff2847afea466/open_spiel/algorithms/tabular_exploitability.cc#L80

The check fails with a somewhat informative error because people have run into this before:

1. Does your game have imperfect recall?
2. Does your State::ToString() not distinguish between unique states?

Our current best-response algorithms require perfect recall. If your game has imperfect recall, this could explain it. For a definition of perfect recall, see [my thesis](http://mlanctot.info/files/papers/PhD_Thesis_MarcLanctot.pdf), page 11-- in retrospect we should really have put that in the OpenSpiel paper. Anyway, I'd eventually like to add a best response algorithm that supports imperfect recall games, which I describe [here](https://github.com/deepmind/open_spiel/issues/464#issuecomment-743977802) but it's not happening any time soon.

Our BR algorithms also cache expected values using the ToString() as keys. So if two different states in your game give the same ToString(), the BR computation won't be right.

**Comment by VitamintK** [comment]
Thanks for the thorough response!  The problem indeed that my `State::ToString()` (`__str__` in python) did not distinguish between some unique states!
