### ISSUE TITLE
Question: information state targetting 

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#49]
I'm trying to rewrite OOS (http://mlanctot.info/files/papers/aamas15-iioos.pdf) and specifically information state targeting.

Part of it is to write a function which takes two ActionObservation sequences and returns if they are compatible (it's possible to get from the current infoset to the target infoset).

In OpenSpiel, neither the `InformationState` / `InformationStateAsNormalizedVector` provide "incremental" information: it's a domain-dependent representation of the whole AO sequence. 
`Observation` or `ObservationAsNormalizedVector` do these "incremental" observations: however how is the observation of "no observation" encoded in phantom games? Empty vector?

Also, do you think it would make sense to store the ActionObservation for each player in State (similarly to how history_ is stored)? It is not possible to do a currentState->parentState lookup, so to retrieve the whole AO for arbitrary state you'd have to make targetted tree traversal from the root to this state. 

I'm asking this specifically in the context of OOS, where you will be given a target infoset (or State, in the Bot API), but you might not know what it's ActionObservations are (if you didn't visit this infoset before and cached it). The result is that you cannot target this infoset efficiently.

**Comment by michalsustr** [comment]
> That seems costly to have turned on by default (since the observations are potentially large vectors)

Did you consider other representation of observations, as the one for neural networks? Maybe something game specific, for example GoofspielObservation which would contain the actual information (win/lose/draw in a round, nature card and possibly cards revealed) from which other representations could be built (such as for neural networks?). These game-specific observations can be much much smaller (probably 1 or 2 orders of magnitude compared to one-hot encoding of doubles :) ). 

>  Support an optional way to turn it on, but have it switched off by default.

I'd be careful about putting more mutability/statefullness into State :) I suggest these kinds of settings should be `const`-ed, i.e. there can be a RootStateFactory(bool capabilityX, bool capabilityY, ...) which sets them up, and disallows user to turn them off later, so that we don't have some states which do have AOs and some which don't. 

I thought about subclassing for type safety, i.e. `StateWithCapabilityX`, but then all other methods will have to return `StateWithCapabilityX`, and make rest of the code type incompatible. This would indeed require templating... _everything_ ... 

This seems like rather a common design problem, so maybe someone with more C++ experience can help? @Dugy

> I can add a bunch of methods that return the collections and/or const refs to them.

I think it would be useful to think about these directly how they relate to information state forests. (thread #1). Who should be the "memory owner" of AOs? State? But then we should be very careful about mutating state into children, because the external AO pointers (for example in the infoset forest) will become corrupt. Maybe this would be an appropriate place for usage of shared_ptr?

> absl::optional<std::vector<std::pair<Observation, Action>>>>

Please avoid the use of std::pair<x,y> in code that should be exposed by the API. It makes the rest of algorithm code full of `.first / .second` statements, obfuscates readability and inhibits programmer's mental type inference (what's this `.first`?). I noticed at many places in the code usage of `x = a.first` anyway to bypass this. I suggest using a simple two-fielded struct, where you can see `.x / .y` and can directly click on it and figure out it's type **fast**. 
In "internal" use (private, maybe protected methods of a class) it's fine, since the "leakage" of these details will be limited.

> I would not be surprised if there was a bug in it (in case you plan to use it, be aware)

Thanks, good to know.

> I don't like the use of complex template magic-- it makes working with C++ unnecessarily complicated... 

I dislike it too and have a friend who helps me with it all the time haha :-) so I understand the sentiment.

**Comment by Dugy** [comment]
> This seems like rather a common design problem, so maybe someone with more C++ experience can help?

I am not sure if I fully understand the context. In case I got it right, this seems like a setting that would apply to all instances. One such property alone can be conveniently handled by various ad hoc approaches, but these tend to accumulate and after adding several such properties, it gets messy. A proper solution may be a variable in some struct with other settings like this passed as a shared pointer or something to all instances, it may be a singleton, it may be a preprocessor macro... all depends on the frequency how often you might want to change it.

**Comment by lanctot** [comment]
> Did you consider other representation of observations, as the one for neural networks?

There are observation strings as well, btw. But, yes, as I mentioned in another thread, this is what Neil did in the Hanabi Learning environment. I think it's ultimately the way to go, but we haven't needed rich observations for anything (yet) because the team who has been using it for research (so far!) has mostly been interested in end-to-end learning algorithms, and we can easily change the observations if we wanted to. 

Probably we'll need to do this eventually because people will obviously want to do more game-specific stuff. Right now, that's not easy in OpenSpiel (by design!) but people will want to define their own observations (and other game-specific stuff) so we ultimately want to support it. In fact we listed it in our [Call for Contributions](https://github.com/deepmind/open_spiel/blob/master/docs/contributing.md).

> I'd be careful about putting more mutability/statefullness into State :)

Sure, I agree generally.  I was suggesting a simple way to support OOS (and another use case I will have soon). We already have a history of integers in there, so it seems natural to complement it with optional (Observation, Action) histories, which seem generally useful, i.e. it will likely be needed again.

The subclassing is not such a bad idea. Or rather, interfaces. Each interface provides a new functionality (pure virtual methods) and only some games can implement them. Since the games are subclassing State already, they would then just need to subclass the interfaces too, and provide those extra methods. Rather than templates this just means down casting, which could make the code a bit awkward and messy, which is why I suggest adding it to State, since it's something that really is generally useful and we have it already.

> I think it would be useful to think about these directly how they relate to information state forests.

My suggestion is avoiding the problems you list because it would _not_ be a pointer to some dynamic structure. I want to avoid that, because then all the clone methods would need to be deep clones and it just makes everything more complicated than necessary.

> Please avoid the use of std::pair<x,y> in code that should be exposed by the API. 

No, I will not. I have had this argument many times, and I remain unconvinced. std::pair is a well-understood type. Every C++ programmer in existence know what .first and .second do. Pairs are perfect for simple tuples, and there is a lot of use cases for two-valued tuples where a struct would be overkill. If every tuple had to use a struct instead, then your code base explodes with custom types and everyone has to lookup what those objects are to understand what is in them (which is terrible for the main core API functions!) Also, your argument with structs implies that people are not naming their variables properly, and we should avoid that. E.g. it is very clear what `action_and_prob.first` and `action_and_prob.second` are, and we should simply make sure these standards are upheld.

> I dislike it too and have a friend who helps me with it all the time

This is *exactly* why they are bad, and I bolded in red letters the "Keep It Simple" design philosophy in the docs and paper. If you need someone's help to do something that the language should make easy, then the answer is not to go to someone else and get help. The correct answer is: don't use those language features. Why? Because it would mean you're narrowing the scope of people that can understand the code (even the implementer doesn't fully understand it!) and it becomes harder to use by everyone. What's worse is that this problem gets even worse over time. If you narrow the scope, then you'll attract more C++ template experts (and alienate everyone else), which means the problem just gets slowly worse over time, until it's basically hard to use for everyone (even the experts). 

C++ has a bad reputation among researches because it's too complex. But that does not need to be the case. It's only "too complex" when you don't guard against complicated language features. The C++ code in OpenSpiel is forcefully simple, and we want to keep it that way. So your aversion to complex use of C++ templates is more than welcome here.
