### ISSUE TITLE
python mccfr objects don't directly return Policies

### ISSUE THREAD

**Issue by VitamintK** [deepmind/open_spiel#499]
Is there a reason that the [MCCFR objects](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/algorithms/external_sampling_mccfr.py) expose a method to get a callable policy (`callable_avg_policy()`) but not a way to get a [`Policy`](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/policy.py) object?

I think we could manually subclass from `Policy` and define `self.action_probabilities(state)` as `cfr_solver.callable_avg_policy(state)`, but is there a reason this isn't built into the MCCFR class already?

**Comment by lanctot** [comment]
I _think_ this is really due to some legacy API from before we had policy objects; IIRC, we sent around callable "things" which represented policies, maybe to avoid storage of full policies? .. but I don't remember very clearly, @elkhrt do you remember... can you elaborate?

So we had to use this policy_from_callable helper to convert them when we made the change: https://github.com/deepmind/open_spiel/blob/6a9cba53cf3fe6ba2c7ed1f310e2e59ec7305484/open_spiel/python/algorithms/outcome_sampling_mccfr_test.py#L47

We should probably change these all indeed to just return policy objects. That would be make a good contribution, feel up to it? :)

**Comment by colibri17** [comment]
Hey there! If @VitamintK has not started to work on it yet, I can contribute! Basically, the point is to make the method `callable_avg_policy` of outcome and external mccfr to return a policy object rather than a callable method, right?

**Comment by VitamintK** [comment]
I have not started work on it, so feel absolutely free to do so.  Obviously @lanctot et al would know much better than me, but I imagine adding an `average_policy` method like in [non-monte carlo cfr](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/algorithms/cfr.py) would be better for consistency with non-monte carlo cfr objects and backwards compatibility.  Not sure if you'd want to then delete the `callable_avg_policy` method though or keep it for backwards compatibility.

**Comment by lanctot** [comment]
@colibri17 , that would be great! I would say let's aim to delete it and add the average_policy method to replace it. I would recommend doing these one instance at a time; for each one there may be many places in the code base that currently use the "callable_avg_policy" and it'll require switching them over to the average_policy. Maybe it'll be easier than I expect, in which one PR might do... but feel completely free to split these into one PR per instance.

**Comment by colibri17** [comment]
Thank you both @VitamintK and @lanctot for the great suggestions. I will implement the `average_policy` method then, which will return a `TabularPolicy` object (as the non-mccfr case) and remove the `callable_avg_policy`. It seems clear enough to me! Will have a look and will split in more than one PR if necessary! Will keep you updated.

**Comment by lanctot** [comment]
Yeah it should be an entire policy as we do in most other places.

Btw in the case of the MCCFR algorithms we probably want a subclass or special instance of TabularPolicy because there should be a "default" policy (e.g. uniform) for info states that were not ever reached. See the C++ implementations for how we did it there, would be good to stay consistent with it if possible.

**Comment by colibri17** [comment]
Ok, thank you for the feedback. Will keep you updated!

**Comment by VitamintK** [comment]
Would it alternatively be possible to just subclass from `Policy`: basically implementing `action_probabilities` with the logic in ` callable_avg_policy`?  This already implicitly returns a uniform random policy for any states not reached, but with the added benefit over a `TabularPolicy` of only requiring `O(number of states reached during MCCFR)` memory instead of `O(number of states in the game)` -- if that would ever be beneficial?

**Comment by lanctot** [comment]
Yeah I think that is what we did on the C++ side so if we can do that here too it'd be great.

**Comment by VitamintK** [comment]
Thanks @colibri17 and @lanctot 😄
