### ISSUE TITLE
module 'pyspiel' has no attribute 'GameInfo'

### ISSUE THREAD

**Issue by willmcgowan** [deepmind/open_spiel#503]
Error thrown when trying to declare the GameInfo of a custom game

**Comment by lanctot** [comment]
We are going to need more. Can you send us a link to the code, or copy it here? Did you start by copying an existing game?

**Comment by willmcgowan** [comment]
I copied the code provided in tic_tac_toe.py into a Jupyter notebook and got the error

**Comment by lanctot** [comment]
Did you use pip to install OpenSpiel? If so, that will be why. We only added that recently, after the last release which is used by the pip package.

**Comment by willmcgowan** [comment]
Yes I did use pip .

**Comment by lanctot** [comment]
Ah yeah that won't work, the new python game structure is too new. You will have to build from source or use the old python tic_tac_toe.py in the 0.2.0 release.

It would make sense to do a minor release to update the pip version since the python game overhaul a few weeks back. I will do it in the next few weeks, please leave the issue open for me as a reminder.

**Comment by lanctot** [comment]
> It would make sense to do a minor release to update the pip version since the recent python game overhaul. I will do it in the next few weeks, please leave the issue open for me as a reminder.

Just a quick update that I'm putting together a release in order to fix this. It necessitated a few other fixes (like https://github.com/deepmind/open_spiel/pull/507 and https://github.com/deepmind/open_spiel/pull/507), and I wrote a test script for the pip packages... it'll be large enough that we're going to stamp it as 0.3.0. So, if not next week then hopefully the week after.

**Comment by lanctot** [comment]
Ok, we've put out a release: https://github.com/deepmind/open_spiel/issues/512, which should fix this.

(You will need to uninstall your pip package and re-install it.)
