### ISSUE TITLE
Optional build of bridge dummy solver

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#528]
Could we move bridge dummy solver as an optional dependency, i.e. `BUILD_WITH_BRIDGE_DUMMY_SOLVER`? I don't know how crucial it is for bridge game evaluation -- is it just a bot? It takes a while to compile and it is probably not used by that many people. I can make a PR that implements this, if it is ok to move it out of the core.

**Comment by lanctot** [comment]
I believe it's necessary for Bridge. If not, I'm super happy to make it optional. @elkhrt can you comment?

**Comment by elkhrt** [comment]
I'd rather keep it if possible. It's needed for the variant of the game where the card-play phase is replaced by the result that optimal perfect-information players would obtain. This is the usual variant used for AI research, e.g. https://arxiv.org/abs/2011.14124

**Comment by lanctot** [comment]
@michalsustr, do you run the script every time you compile? If you just run make in the build dir, it should not recompile this every time unless you touch some of the main core files like spiel.h etc.

Likewise in testing you can just run the tests directly to avoid rerunning them all each time.

Asking because several of your past threads have been about speed, but you'd only be affected by this if you recompile everything from scratch each time.

**Comment by michalsustr** [comment]
@lanctot I don't run the build_and_run_test script every time, however when I switch git branches a large number of files is typically modified, causing recompilation of pretty much the whole project (especially if CMakeLists are modified). Maybe Bridge could be done similarly to Hanabi or ACPC? But if you prefer to keep it in that's ok.

I'm planning to get a new PC which would solve most of these issues :) (but waiting for GPU prices to drop, it's insane right now...)
