### ISSUE TITLE
Best response computation for sim-move games

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#531]
Currently sim-move games have to be transformed to sequential games in order to compute best response (and exploitability). This adds overhead and if I remember well it doesn't work too well with observations / observer API.

The way BR works it essentially constructs the entire history tree along with infostates for the players, keeps track of the decision states and is making non-trivial recursion and updates for the BR calculation, in order to make the response computation consistent with the decision space of the responding player. 

Infostate trees do all of the above points (construct the entire game with infostates, keep track of decision states, etc.). Additionally they work with sim-move games out of the box. The BR calculation is very simple, it is just a greedy recursive traversal of the infostate tree for the responding player.

I would like to propose swapping the implementation of BR that uses history tree with infostate trees. Let me know if you agree, I can make a PR which implements this. Additionally, this would make the history tree obsolete, as it is used only by BR within the repo, and is therefore a candidate for removal.

I raised this somewhere before, but only now got time to take a look at it. Tagging @finbarrtimbers and @lanctot

**Comment by lanctot** [comment]
Hi @michalsustr , it would be great to support proper best response for simultaneous move games. However, I think there's a better way to do it, that I described here in this thread: https://github.com/deepmind/open_spiel/issues/464. Using the (infostate) MDP approach has the advantages of:

1. Properly supporting perfect info games
2. Properly supporting imperfect recall games
3. Taking space linear in *info states* rather than in histories.

I think having it support simultaneous move games is not much extra work, and you'd get the benefit that it supports imperfect recall simultaneous move games too. I am guessing what you have in mind does not achieve (3). 

So if we go through a bunch of effort to improve the BR, would be good to just go the extra mile and support all these.

I have an internal implementation that I'd need to adapt first, and you can add simultaneous move games to it. Wdyt?

BTW I assume we are talking about the C++ side.

**Comment by michalsustr** [comment]
I like this idea :) As you explained it handles the imp. recall, unlike constructing the tree(s). What do you use, dynamic programming? Once it's out I can add the sim-moves. Is the plan to integrate it with exploitability calculation? (Maybe the exploitability/nashconv functions can take BR as a callback. Then it would compose nicely with ABR to yield ApproxNashConv)

> BTW I assume we are talking about the C++ side.

Yes.

**Comment by lanctot** [comment]
Yeah exactly: the internal one I wrote basically just runs value iteration on the resulting MDP.

So I'm happy to do this, but I have no idea when I'll get to it. Might be a few weeks.

**Comment by lanctot** [comment]
Good news, I finally got around to doing this. Should be merged in the next sync. However, there seems to be a problem with Goofspiel -- I suspect it's related to the observations, possibly they are missing something. @michalsustr, can you take a look when it's merged?

**Comment by lanctot** [comment]
Ok @michalsustr can you see the commit linked above and check the case for simultaneous moves? It's failing for goofspiel, could be a bug in my impl, but could also be a bug in the goofspiel observations.

**Comment by michalsustr** [comment]
Ok I will try to take a look over the weekend. If I recall correctly I did fix observations in a number of games, I just didn't prioritize to make PRs at the moment. Last time I checked I made 500 commits apart from master, so that will be "fun time" merging everything after deadlines :)

**Comment by lanctot** [comment]
Hah, no rush. I may try to come back to it as well when I have a bit of time for it. For now I just put a warning that there's a known problem in the tests for the case of simultaneous move games.

**Comment by lanctot** [comment]
Now fully working as of https://github.com/deepmind/open_spiel/commit/898ea51ae6ce4f34c788007ba710cf3ced127ca4, but the observations need to be Markovian, which required a change to Goofspiel. See the comment in the header for clarification.
