### ISSUE TITLE
Any plan for adding ReBeL algorithm?

### ISSUE THREAD

**Issue by lilith829** [deepmind/open_spiel#535]
Hi,

I saw the public state API in the repository with kuhn poker available. 
I wonder if there is any work in progress to add ReBeL algorithm. 
Thanks.

**Comment by lanctot** [comment]
I would love to see an implementation of ReBeL in OpenSpiel.

Public states are really fundamental to the algorithm. I think the feasibility would depend on the current state / maturity of the public state API. @michalsustr, what do you think?

It'd also be great if it was contributed by one of the original authors, or if they were involved with reviewing. @noambrown, @akhti: is there any interest on your side, or do you know anyone who might be interested? 

Note that there is an open implementation on Liar's Dice here: https://github.com/facebookresearch/rebel. Can anyone say a bit about how difficult it would be to adapt this to OpenSpiel?

**Comment by michalsustr** [comment]
I would love to see that as well. 

I had a look at how public states are done in the linked implementation and I think it would be easier to just use that implementation, and provide only a very loose integration with OpenSpiel. I am not sure how well that code can be incorporated in the OpenSpiel codebase, in the sense of running OS algorithms for Rebel results (like computing exploitability using OS code, making a bot, etc.). Most importantly, it certainly won't run on arbitrary game loaded from OS (like Leduc), because it needs a reimplementation of every OS game to work directly on the public tree. This limits the usefulness of the integration. There can be workarounds for small games -- generate the public tree from all the histories within the game. If you are interested in that, I can try to help.

**Comment by lanctot** [comment]
Yeah I'm not sure that level of integration makes sense.

I was talking about doing it "properly" via the Public States API you started. Can you elaborate on the technical reasons as to why we wouldn't want to get it to the point where we can run/implement ReBeL? 

Is it because each game would need to be re-implemented with a "public states first" sort of API?

**Comment by michalsustr** [comment]
> Is it because each game would need to be re-implemented with a "public states first" sort of API?

Yes, and the "generate all histories" workaround can be used only for small games, where you can run more efficient algorithms anyway.

**Comment by lilith829** [comment]
Thanks Marc, Michal. I wonder if it's possible to add it as an example algorithm in public state, like CFR. Kuhn poker implemented with public state API can be the target game.

**Comment by michalsustr** [comment]
Sure, that can be done. Write me an e-mail.
