### ISSUE TITLE
cfr calculation problem in the implementation for deep cfr

### ISSUE THREAD

**Issue by dvstter** [deepmind/open_spiel#536]
`    else:
      other_player = state.current_player()
      _, strategy = self._sample_action_from_advantage(state, other_player)
      # Recompute distribution for numerical errors.
      probs = np.array(strategy)
      probs /= probs.sum()
      sampled_action = np.random.choice(range(self._num_actions), p=probs)
      self._strategy_memories.add(
          StrategyMemory(
              state.information_state_tensor(other_player), self._iteration,
              strategy))
      return self._traverse_game_tree(state.child(sampled_action), player)`
In the code line314-325, when the current player is not the updating player, the function _tarverse_game_tree will return the child node's utility directly which is not coincided with the original definition for CFR.

To be more specific, these code's defintion for CFV and CFR are:
![CodeCogsEqn](https://user-images.githubusercontent.com/11886450/111258928-e7416a00-8658-11eb-95e2-0782bb0efa27.gif)

But the original definition for these are:
![CodeCogsEqn (1)](https://user-images.githubusercontent.com/11886450/111258813-aea19080-8658-11eb-8472-2b8dbbe9b347.gif)

We can see that these equations differ one factor which is:
![CodeCogsEqn (2)](https://user-images.githubusercontent.com/11886450/111258849-be20d980-8658-11eb-9655-804bb14e2651.gif)

I cannot find any modification in the origin paper <Deep Counterfactual Regret Minimization>. So these modifications are okay? Will it changes the boundary for the accumulative regret?

**Comment by lanctot** [comment]
Hi @dvstter, yeah that's because Deep CFR uses external sampling, so that term cancels with the denominator when you do the importance sampling. For example, see the C++ update here: https://github.com/deepmind/open_spiel/blob/47492034bc4124464d8258da63ee8a90ccf6edf2/open_spiel/algorithms/external_sampling_mccfr.cc#L169

Super happy to explain why in more detail, but I guess that should also be the case in the Deep CFR pseudo-code from the original paper. If you want to dig more into why, I'd say my thesis chapter 4 is a great place. :)
