### ISSUE TITLE
How to run PyTorch agent on GPU?

### ISSUE THREAD

**Issue by ThierryDeruyttere** [deepmind/open_spiel#538]
Hi,

We have been trying to get the PyTorch agents provided by OpenSpiel on our GPU.
Normally you can do this with `.to("cuda:0")` on an nn.Module. However, the agents are a subclass of `rl_agent.AbstractAgent`which does not provide such a method.

**Comment by lanctot** [comment]
I have not done this myself. @Asugawara, @ssokota, @MJ10: any ideas?

**Comment by MJ10** [comment]
Apologies for the slow response. I think this would require some changes in the agent class:
1. Add a device parameter to the constructor. 
2. Within the agent class move the networks to the specified device. 
for example, in [DQN](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/pytorch/dqn.py) after [Line 229](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/pytorch/dqn.py#L229) move the `self._q_network` and `self._target_q_network` to the specified device (using `.to(device)`)
 
3. Before a forward pass on some input tensors, move them to the device. 
continuing the DQN example, before [Line 341](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/pytorch/dqn.py#L341) move the `info_state` using `info_state.to(self.device)`. Similar changes would be needed on L380 and L381. 

This would need to be added for all the agents. 
Although, I did try something like this a while back, on the games I tested it was much slower, possibly since the networks aren't that big and moving the data to the GPU so many times itself takes more time. But I might be missing something.

**Comment by ThierryDeruyttere** [comment]
Ok, thanks for the answer! Is it then possible to run the models on GPU with TensorFlow?

**Comment by lanctot** [comment]
Thanks @MJ10 ! That sounds like a minimal change.. @ThierryDeruyttere why don't you make the change locally for the agent you want to use and run that?

We have not spent any time supporting GPUs generally, it would make a nice contribution. If it works for the one agent as @MJ10 suggests, we can start there and maybe make a general solution?
