### ISSUE TITLE
How to invoke `ToTabularPolicy` from python?

### ISSUE THREAD

**Issue by VitamintK** [deepmind/open_spiel#543]
I can invoke `ToJointTabularPolicy` with `pyspiel.to_joint_tabular_policy` but I can't figure out how to invoke `ToTabularPolicy` ([policy.h](https://github.com/deepmind/open_spiel/blob/master/open_spiel/policy.h)).  (My end goal is to turn a C++ CFR policy into a C++ tabular policy, to turn it into a python tabular policy, so if there's a better way to do that then I can do that instead.)

**Comment by lanctot** [comment]
There's now way to do it currently. 

Here's an inefficient way to achieve what you want:
1. Add the following line:

`.def("tabular_average_policy", &open_spiel::algorithms::CFRSolver::TabularAveragePolicy)

right after this line: https://github.com/deepmind/open_spiel/blob/b07e3ba2838c32be8f598abc705b886e64d75101/open_spiel/python/pybind11/policy.cc#L116 

2. Then use `pyspiel.python_policy_to_pyspiel_policy` here: https://github.com/deepmind/open_spiel/blob/b07e3ba2838c32be8f598abc705b886e64d75101/open_spiel/python/policy.py#L398

It's inefficient because the `TabularAveragePolicy` function does a full game traversal querying the underlying policy at all information states to construct the policy. This should be fixed: for the non-sampling methods to just do a linear scan through the CFR info set tables and construct the policy by hand, and for the sampling methods have an option to decide which one you want (a complete policy may require the tree traversal, but the caller may not need a complete policy). So, please leave this issue open as a reminder for me to fix this eventually: the TabularAveragePolicy should be exposed to python and it should be more efficient.

**Comment by Henry-E** [comment]
Not sure if this is the right place to ask. Even though running `type(solver.average_policy())` now returns `TabularPolicy` it has almost none of the same methods on it as the `TabularPolicy` defined in `policy.py`?
```
dir(solver.average_policy()) ->
'action_probabilities', 'get_state_policy', 'get_state_policy_as_map'
```
These are the only three methods available on the `TabularPolicy` type return by the CFR solver?

Whereas the methods on a true `TabularPolicy`, loaded using the standard `policy_lib.TabularPolicy(game)` are much more extensive.

``` 
dir(policy_lib.TabularPolicy(game)) ->
 'action_probabilities',
 'action_probability_array',
 'copy_with_noise',
 'game',
 'game_type',
 'legal_actions_mask',
 'player_ids',
 'policy_for_key',
 'state_in',
 'state_index',
 'state_lookup',
 'states',
 'states_per_player',
 'to_dict',
 'to_tabular']
 ```
 
 Is there something I'm missing here or are there two different `TabularPolicy` classes?

**Comment by lanctot** [comment]
Yeah can you open a new separate issue for this? (I don't know the answer off the top of my head, have to investigate)

**Comment by Henry-E** [comment]
Sure, sorry I thought this might be the right place but i'll make a new issue with it.

**Comment by elkhrt** [comment]
You should be able to convert it to a Python tabular policy using pyspiel_policy_to_python_policy. Let us know if it works!

**Comment by Henry-E** [comment]
Sorry, I opened another issue and commented that i'd found the solution going through source for pyspiel. Thanks!

**Comment by lanctot** [comment]
Great, closing again!

**Comment by lanctot** [comment]
For others' reference, here's the issue you're referring to: https://github.com/deepmind/open_spiel/issues/994
