### ISSUE TITLE
Defaulted parameters are not inferred from GameType

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#546]
`Game` has a map of params called [`defaulted_parameters_`](https://github.com/deepmind/open_spiel/blob/41f76e32b11165b0693c84c077134e65cbd7f4b9/open_spiel/spiel.h#L951), while `GameType` has also a map of params called [`parameter_specification`](https://github.com/deepmind/open_spiel/blob/41f76e32b11165b0693c84c077134e65cbd7f4b9/open_spiel/spiel.h#L123) which also uses default values.

I find this very confusing. For example, a game may specify which parameters it uses, but then if you call MyGame::GetParameters(), you do not get the defaulted values, **unless** the game uses the `T Game::ParameterValue` method call (and to add to the confusion, that call can also provide _another_ defaulted value). I stumbled upon this in universal_poker.

I'd like to suggest that there should be only the (immutable) GameType.parameter_specification. The Game receives a set of parameters and makes a union of them and GameType.parameter_specification in the constructor, and saves it into its internal immutable map of game_parameters_. These will be then accessible to DerivedGame and can use ParameterValue in their constructors as to avoid string lookups in the param map, and these saved members should be typically marked as const.

WDYT?

**Comment by lanctot** [comment]
Yeah I think this is generally a good idea, and I've thought about it myself a few times too. It's a huge change to make now, though.. are you sure you're up to it? 

I remember when @elkhrt added the `ParameterValue` member functions, wondering why we didn't make the change at that point. I expect there was a technical reason that made sense.. Ed, do you remember? Seems like something we would have changed when we were doing those early sweeps through all the games.

The problem is now there's a lot more built on top: game parameters are now serialized, so we'd have to make sure that all still works... and we have python games. I'm thinking there might just be something preventing this from being possible or easy, and I'd only like to make the change if we can do it properly without leaving something broken (that currently works).

So I'm in favor, but would like Ed's thoughts. Maybe wait a day or two until he responds before working on this.

**Comment by michalsustr** [comment]
Makes sense. It is not high priority -- I might get to it some time (but not soon). I will make a comment when I do. If anyone wants to change it in the meantime, feel free, and please leave a comment :)
