### ISSUE TITLE
Should __str__() have perfect recall?

### ISSUE THREAD

**Issue by VitamintK** [deepmind/open_spiel#565]
Should `__str__()` have perfect recall? I ask because it looks like for `tic tac toe`, `battleship`, and `oshi_zumo`, the `__str__()` does not have perfect recall, e.g.:
```
ox.
.o.
x.x 
```

I think this is causing issues with the way that the BR caches `.value()` 

Here's a demo I ran (can supply the policy action_probability_array to repro `my_policy` if anyone is interested):
```
from open_spiel.python import policy
from open_spiel.python.algorithms import expected_game_score
from open_spiel.python.algorithms import best_response

game = pyspiel.load_game('tic_tac_toe')
[... make `my_policy`...]
br = best_response.BestResponsePolicy(game, 1, my_policy)
print(expected_game_score.policy_value(game.new_initial_state(), [my_policy, br]))
print(br.value(game.new_initial_state()))

output:
[-0.00004046  0.00004046]
0.933332725976865
```

I believe the expected outcome is that they should have the same value, e.g.:
```
[-0.00004046  0.00004046]
0.00004046
```

An alternative fix could be to memoize `best_response.BestResponsePolicy.value` by `history_str()` instead of `__str__()`.

**Comment by lanctot** [comment]
Short answer: no.  `__str__` calls `State::ToString` which is a string representation of the state, which does not require perfect recall. And it's shouldn't be required to have perfect recall because there are times when it makes perfect sense for it not to, like in the case of Markovian states like Tic-Tac-Toe. 

Yes, our best response algorithms use the ToString as a key representation of the state for determining the value of the state, so when using the best response or exploitability functions, it's fine as long as the value of the state is equivalent for all histories that lead to it. 

It is "well known" that the current best response algorithms don't work in perfect information games (though maybe we should document this) and I have a plan to add one that will. See #464 and #531 for discussion. It will also be able to do simultaneous move games and imperfect recall games. I plan to add it in the near future, I hope I can get to it before the release.

**Comment by VitamintK** [comment]
I fear there may be no quick fix to allow memoizing BRs to treat states belonging to the same markovian state as identical, since "the value of the state is equivalent for all histories that lead to it" may not be true since *policies* in general are per infostate, not Markovian state.

That is, my open_spiel policy could have me playing action A if the tic-tac-toe sequence (aka infostate) is `1 0 3` but I could play action B if the sequence is `3 0 1`.  So a fix that still allows caching by Markovian states would have to ensure that the policy that's being BR-ed to is also "intra-Markovianly blind", no?  Not sure if this concept already exists in open_spiel or not.

**Comment by lanctot** [comment]
I agree there is no quick fix to the current BR impl. I'm currently implementing a new best response algorithm that will handle this properly, in the sense that policies can be based on observations (i.e. Markovian descriptions of states in perfect info games like Tic-Tac-Toe) and uses value iteration to find the BR. Please see the issues I linked in my last response for more detail. I finished the implementation this week; it should be merged in the next sync (Monday).

**Comment by VitamintK** [comment]
Ah, I see.  Thank you, sounds great!

**Comment by lanctot** [comment]
Hi @VitamintK , the new BR I mentioned is now live from this commit: https://github.com/deepmind/open_spiel/commit/110a2a724d35d880ff1025725f2586a43f472167. You can find it in `algorithms/tabular_best_response_mdp.*` It's not overly tested but I did check that it matches the value of the current BR to random in TicTacToe (but is a lot more space efficient using only 4520 Markovian observations rather than hundreds of thousands of information states). Please let me know if this helps!

**Comment by VitamintK** [comment]
Thanks @lanctot, looking forward to checking it out.  How does this behave if the policy being best-responded to has a different policy for, e.g. sequence `1 0 3` and `3 0 1`, both of which are the same Markovian observation?

**Comment by lanctot** [comment]
That is not currently supported: it uses information state strings as the keys or observation strings, and it's dynamically decided based on the game type (btw is there a reason or specific use case you can describe where that would be useful?)

You could modify the code to get this if you can just use observation strings when you build the MDP for the best-responding player but use information state keys for the fixed player(s), and then change this function here: https://github.com/deepmind/open_spiel/blob/643dfd2a5ef023e796e20d06758800ec34a1204b/open_spiel/algorithms/tabular_best_response_mdp.cc#L273

But then you'll need a policy in information states while the BR will use observations. I would guess that it's easier to just use one or the other and convert between them as necessary. E.g. you can make a function that converts a policy with information state string keys to observation string keys or vice versa. 

I might need more context.. I feel like I'm not really helping answer the question you want answered. Can you describe why you want that?

**Comment by VitamintK** [comment]
The original motivation was that I had a policy for tic-tac-toe that I wanted to measure exploitability for.  I found that `exploitability` was reporting incorrect exploitability due to the BR caching values by `ToString` rather than infostate.  If the values were incorrect, I think that means that my original policy did not fulfill the requirement where "the value of the state is equivalent for all histories that lead to it."  I'm not sure why it was that way (I was making the policy in a double-oracle kind of way), but in general, policies don't fulfill that guarantee, right?  

Maybe the question I meant to ask is: How should we use these new Best Responses?  You mentioned a policy with observation string keys -- Is there an explicit OpenSpiel concept of a policy based on observations instead of infostates?  Could I, for example, get a policy from CFR and use this new BR against that, or would that not be supported?

**Comment by lanctot** [comment]
Ok.. I was all kind of confused throughout this thread but now I think I finally understand. Sincere apologies for the runaround.

You are talking about the python best response, and it does indeed have the problem you initially described. We also had this on the C++ side, and we changed it to use State::HistoryString as keys instead of ToString several months ago. But we did not make the same change on the Python side, which we should. Thanks for finding this -- once we fix it, you should be able to compute the best response for policies in information states just like the C++ one currently can.

Onto your next question. The new MDP best response implementation I don't think will be useful to you (yet). I mistakenly understood that you were using the C++ best response. The new MDP best response is only in C++ (we can easily expose it to python though, and we will, once we resolve the problem with the Goofspiel test). Right now the way to use a policy based on observations is to override and use `Policy::StatePolicy(const State& state)` or fill the `TabularPolicy` yourself using observation strings as the keys instead of infostates. The CFR policy will always be in information states, but if you change all instances of information_state_string to observation_string in the CFR impl that should give you a tabular policy based on observations (I'm not 100% sure our CFR would work on perfect information games, though, even with this -- so tread carefully). 

I believe your issue will be resolved when we fix the Python BR to use `history_string` instead of `str`. Maybe you can try and see? If so it'd be great to submit a PR to fix it, as I'm not sure when I'll get to this :(

**Comment by lanctot** [comment]
Also tagging @finbarrtimbers @elkhrt who have done a lot of work on these implementations.

**Comment by elkhrt** [comment]
This will be fixed in the next push to github. Sorry it's taken so long!
