### ISSUE TITLE
Issues regarding incomplete docker related handlings

### ISSUE THREAD

**Issue by uduse** [deepmind/open_spiel#592]
Since OpenSpiel's development is quite healthy (actively developed and many tests), I assumed that I could use docker smoothly. This is the promise of docker, after all. However, this was not the case. Here are some observations of mine after trying to build and run docker stuff with OpenSpiel. If I missed some important information somewhere, please let me know!

### documentation inaccurate
The command in the documentation doesn't work. It has a syntax error (missing build path, usually the current directory `.`).

```
> $ docker build --target base -t openspiel -f Dockerfile.base --rm                                                                                                             

"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
```

### building an image from `Dockerfile.base` doesn't work out-of-the-box
I tried building docker images using `Dockerfile.base` on both macOS and Linux, and both them needed extra care. More specifically, I had to insert `pip3 install tensorflow` somewhere to make it work, otherwise, `python_policy_gradient_test` would fail. 

### no related tests
AFAIK, there are no docker-based tests running in github actions. I think the Dockerfile is outdated now but since there are no related tests I don't know what broke it.

### proposed solution
I think OpenSpiel should build docker images using github actions and host the built images using github packages. [I made an example of this workflow here](https://github.com/uduse/docker-based-research-workflow/packages/280208). This way, users could pull docker images and run OpenSpiel inside of it directly without going through the hassle of building it.

**Comment by lanctot** [comment]
Thanks @uduse. 

Thanks for flagging. Not many of us use docker, so it does indeed get left behind since there are no tests. I will put a note on the docker installation to make this clear.  

The missing tensorflow can be fixed by sourcing scripts/python_extra_deps.sh and installing the extra python dependencies (we do that in our github actions tests, see here: https://github.com/deepmind/open_spiel/blob/53eeb6127578f91e88a6c0451983d10e3509446d/open_spiel/scripts/travis_script.sh#L53). We can add it to the docker script too.

Can you submit a PR that fixes this and the typo problem in the docs?

I understand your proposed solution, but that level of support for something only used by a small fraction of the user base falls just short of what we can realistically fit into our maintenance and support time toward OpenSpiel. So, we will have to rely on community contributions for this kind of stuff. Would you be willing to prepare an OpenSpiel installation workflow like the one you point to? (This PR: https://github.com/deepmind/open_spiel/pull/161 is probably relevant; notice it was submitted more than a year ago-- but we have not gotten around to it because there's always more important things to get to.

That said, @elkhrt was talking recently about looking into getting our tests moved to Docker so that we can test internally and externally using the same environment. This would also address your last problem. So maybe we can get better support for Docker in due time. I'm happy if we go that way, but I just don't have the time to spend on it myself.

**Comment by uduse** [comment]
@lanctot Thanks for the info. I don't think I can confidently provide the right fix for the Dockefile right now as I fixed it in different ways on different platforms in order for it to work. We should worry about it later when we have cross-platform tests for that.

Here's the plan. I will tinker with the docker stuff on my forked repo and use it for a while to make sure it works as intended. When I think it's ready or when you think it's time to embrace docker in tests here, I will create some PRs for the related changes. Sounds good? 😃

**Comment by lanctot** [comment]
Hi @uduse, also wanted to mention this PR from way back, which seens relevant:  https://github.com/deepmind/open_spiel/pull/161/files
