### ISSUE TITLE
Some implementation problem about the ARMAC.

### ISSUE THREAD

**Issue by dvstter** [deepmind/open_spiel#614]
Hello, I am sorry to contact @lanctot in this way, but I cannot find any personal email or anything. 
I am a researcher focus on the CFR. Recently I am working on implementing the ARMAC.
In this paper, I have some problems, anyone could help me on this?

First one: 
<img width="812" alt="Screen Shot 2021-05-24 at 10 12 31 PM" src="https://user-images.githubusercontent.com/11886450/119361157-ec1c3d00-bcdd-11eb-8304-26b11b77e20c.png">

Second one:
According to this article, the W is mapping state S to actions' accumulative regrets conditioned on some value to avoid Importance sampling. But this value is used to predict advantage value based on the history h and action a. And we all know that the state s is not equal to history h. So this is right?
<img width="390" alt="Screen Shot 2021-05-24 at 10 21 49 PM" src="https://user-images.githubusercontent.com/11886450/119361724-8f6d5200-bcde-11eb-8172-5f7f389f77a5.png">

If anyone could help me with this problem, I could not be possible to more thankful.

**Comment by lanctot** [comment]
Hi @dvstter,

Most of my papers have my email contact on them, and it's also available from my web site too. I will answer these here but prefer not to use the OpenSpiel forums for this purpose, so if you have any more question feel free to follow-up by email.

For the first question, indeed the v_{\theta^t}(h) (and q_{\theta^t}) are not used in epoch t, since j is sampled from 0 to t-1. These are just defined here for future epochs (t' > t). They could even have been defined in the text only, they don't really need to be in the pseudo-code of Algorithm 1.

For the second question: \bar{W}_i^t(s,a) is an estimate of the average regret, up to a multiplicative factor (that only depends on the information state s). And yes it is trained by regression toward regrets based on the *conditional* advantage A_{\mu^t,i)(h,a): the condition is that h \in s and h is sampled according to the mixture policy \mu^t. Notice that it estimates the *expected* advantage of h \in S, which is a sum over h \in s where each h is weighted by Pr(h) given \mu^t.
