### ISSUE TITLE
PSRO Symmetric game question. 

### ISSUE THREAD

**Issue by zhz44** [deepmind/open_spiel#632]
Hi, 

I am trying to understand how the symmetric game works in PSRO solver. When I am running the PSRO kuhn/leduc experiments from https://github.com/aicenter/openspiel_reproductions, if I set the symmetric to true in the PSRO solver, the computed exploitabilities keep increasing rather than converge to 0 as the game progress. I am wondering why is this, thank you.

**Comment by lanctot** [comment]
Hi @zhz44, I will ask the original author, but can you say more about your motivation? Those games are not symmetric, so I would not expect that to work.

**Comment by PaulFMMuller** [comment]
Hi @zhz44 ! I'm the author :)
Yes, Kuhn and Leduc are not symmetric games. Iirc, what the `symmetric` option does is that it considers that player 0's policies are all players' policies; since the game is symmetric, this is a valid assumption. The meta-solver is also forced to be equal over all players. Same, since the game is symmetric, all players should take the same optimal distribution of play.

Since Leduc and Kuhn aren't symmetric though, I suspect what you're seeing is due to taking policies that were trained on player 0's infostates, and running them on player 1's infostates, which they weren't trained on ! Another possibility is that the metasolver is spitting different distributions (Extremely likely) for player 0 and player 1, and that players are playing an increasingly wrong distribution.

Hope that helps,

Best,

Paul

**Comment by MachengShen** [comment]
Hi,

I'm also interested in solving symmetric games in PSRO. I guess it is because of the fixed sequence of game play that makes kuhn/leduc asymmetric, right? 

Is there another game which is symmetric that I can use instead? Thanks!

**Comment by PaulFMMuller** [comment]
Hey Macheng,

It is partly because of that, partly because the second player sees the first player's action and reacts to it (The first player checked ? Raised ? Or even folded ? All of these advantage me, as they bring quite some information to me that the first player didn't have when it made its first decision)

As far as symmetric games are concerned, I'm not too sure. I think @lanctot will be better informed than I. Any game with a first move - second move difference won't be symmetric (So no Chess or Go). Instantaneous-move games should be more likely to be symmetric, I think blotto should work, but not sure if we have anything extensive-form-symmetric !

**Comment by lanctot** [comment]
Yep thanks @PaulFMMuller. Some of the simultaneous move games are symmetric: Goofspiel, Oshi-Zumo. Tiny Hanabi, too, I think.
