### ISSUE TITLE
Replay Chance Outcomes

### ISSUE THREAD

**Issue by julianhartmann1** [deepmind/open_spiel#667]
Hello,

I was wondering if there is an easy way to replay certain chance outcomes switched for the players in order to be able to better evaluate the performance of differently trained agents. I would be especially interested in doing so for the game leduc poker, so the goal would be to play a game and in the following game the cards of two agents are switched.

**Comment by lanctot** [comment]
Hi @julianhartmann1, no we don't have anything like that implemented. I think it would have to be tailored to each game because they're no easy way to associate which chance nodes distribute private information to which player (and in some cases that's not even done by separate chance nodes like in our Leduc and Kuhn poker implementations).

I'd say the easiest way to achieve that-- assuming you are training your agents using through the rl_environment-- is to fork the rl_environment (or just change it locally) and add some extra accounting within it to track which chances events have been sampled for the individual players, and then swap them when the other player plays. Like I said above, it'll have to be game-specific so you'd need to a separate version for each game.

**Comment by lanctot** [comment]
Hi @julianhartmann1, I assume it's all clear, so I'm closing the issue. Please reopen if you need to follow-up!
