### ISSUE TITLE
Error in rl_environment.py

### ISSUE THREAD

**Issue by menglinjian** [deepmind/open_spiel#702]
when I run:
game = 'leduc_poker'
env_configs = {"players": num_players}
env = rl_environment.Environment(game, **env_configs)

one error rasised:
 File "/mnt/d/ubuntu/venv/lib/python3.8/site-packages/open_spiel/python/rl_environment.py", line 318, in step
    self._state.apply_action(actions[0])
pyspiel.SpielError: /tmp/pip-req-build-muvq_yxe/open_spiel/games/leduc_poker.cc:392 num_raises_ < kMaxRaises
num_raises_ = 2, kMaxRaises = 2

I think is that you use actions[0] to execute, not legal_actions[0]. And not only in leduc_poker, in many other environments,  the error will also rasise.

**Comment by lanctot** [comment]
Hi @menglinjian,

actions[0] is the correct value there, as the environment step function receives action ids in the range [0, game.num_distinct_actions()).

What you are seeing is a failure due to submitting an illegal action to the environment. By default, this will fail inside the game's ApplyAction environment (such as when trying to raise when you have used the maximum number of raises).

You can enable an action legality check by setting this environment flag: https://github.com/deepmind/open_spiel/blob/38941dee3beb52ffdb134b66f420a758634d9a20/open_spiel/python/rl_environment.py#L156

So you need to figure out why your agent is choosing illegal moves.

**Comment by menglinjian** [comment]
> Hi @menglinjian,
> 
> actions[0] is the correct value there, as the environment step function receives action ids in the range [0, game.num_distinct_actions()). The agent must submit legal actions.
> 
> What you are seeing is a failure due to submitting an illegal action to the environment. By default, this will fail inside the game's ApplyAction environment (such as when trying to raise when you have used the maximum number of raises).
> 
> You can enable an action legality check by setting this environment flag:
> 
> https://github.com/deepmind/open_spiel/blob/38941dee3beb52ffdb134b66f420a758634d9a20/open_spiel/python/rl_environment.py#L156
> 
> So you need to figure out why your agent is choosing illegal moves.

Thank you for your answer,  I have solved this problem.

**Comment by lanctot** [comment]
> Thank you for your answer, I have solved this problem.

Great! You're welcome.
