### ISSUE TITLE
Question about interfacing OpenSpiel with agents/games running in other processes

### ISSUE THREAD

**Issue by uozuAho** [deepmind/open_spiel#728]
Hi there, I'm interested in using OpenSpiel to play games implemented in other languages. An example: I have a game implemented in C# - I don't want to reimplement it in C++/Python, and I don't want to implement OpenSpiel algorithms in C#.

Is there an existing way to get OpenSpiel communicating with games/agents running in other processes? I couldn't find anything. I'm happy to have a go at implementing something, but thought I should ask first.

My current thinking is a text-based interface over sockets. Hopefully this will be simple and portable.

**Comment by uozuAho** [comment]
An update: I've got a basic version of what I want working in Python here: https://github.com/uozuAho/open_spiel_playground/tree/main/zmq_ttt

Some questions:
- Do you want the python version contributed to this codebase? My C++ is a little rusty, so it'll take me a while to get the same thing running in C++.
- Is the use of [ZeroMQ](https://zeromq.org/) OK for the networking part? I'm not very familiar with networking, so I went for something that abstracts away the low level details. Similarly to the above point, I could have a go at using plain sockets or the code in higc/, but it will take me some time, and risks ending up falling down my to-do list :)

I won't be offended if the answer is no to both :)

**Comment by lanctot** [comment]
> An update: I've got a basic version of what I want working in Python here: https://github.com/uozuAho/open_spiel_playground/tree/main/zmq_ttt

Wow.. I have to say, I'm quite impressed :) 

>     * Do you want the python version contributed to this codebase? My C++ is a little rusty, so it'll take me a while to get the same thing running in C++.

Maybe, with some changes. I'll discuss it with the team. I think having Python implementation is ok, if you're willing to support it. C++ would be better integrated with the library, but it's also some work.. so might be oke to just have a working Python example.

>     * Is the use of [ZeroMQ](https://zeromq.org/) OK for the networking part? I'm not very familiar with networking, so I went for something that abstracts away the low level details. Similarly to the above point, I could have a go at using plain sockets or the code in higc/, but it will take me some time, and risks ending up falling down my to-do list :)

This part I like less. For such simple network communication it might better to just use vanilla socket communication. But also: not necessarily a show-stopper since it seems to be [available in PyPI](https://pypi.org/project/pyzmq/22.3.0/). Is that what you used.. i.e. you installed ZeroMQ via pip?

BTW, couldn't help but notice you plan to run stuff on Pandemic. Very cool! Super fun game, but honestly haven't been able to play it in the past 1.5 yrs :) I'd be quite interested to hear about some RL methods running on Pandemic. We have an implementation of AlphaZero too if you want to use search.

**Comment by uozuAho** [comment]
Hmm I don't think I could commit to supporting it, so it's probably best kept separate for now. I also understand the hesitance about ZeroMQ. It was a lazy choice of mine, and is very likely an unnecessary dependency. I did install it via pip, but I guess it probably wouldn't be that hard to make it use regular sockets instead. Thanks so much for the advice anyway!

I'll give AlphaZero a go on Pandemic when I can, thanks for the tip. I've been slowly dabbling with AI, and had plans since pre-COVID times to use it to see if it's possible to consistently win with 6 epidemic cards. I haven't yet got a full implementation of the game working - that's another item on the to-do list :)

**Comment by lanctot** [comment]
Closing as outdated, but it'd still be fun to have a network-based game implementation for doing it in other languages!
