### ISSUE TITLE
Backgammon PubEval bot

### ISSUE THREAD

**Issue by jamesdfrost** [deepmind/open_spiel#74]
Looking for some guidance - keen to implement the backgammon PubEval bot for benchmarking backgammon game performance. The original code is in C++ and would rather implement in this if possible, but all the existing bots are written in Python - is it possible to write a C++ bot, or is there a smarter way of doing this?

I can convert the code to Python if necessary, but just want to know if there are other options first.

**Comment by lanctot** [comment]
Hi @jamesdfrost ! It is perfectly fine to have C++ bots; that's why we have the both API in C++ and the Pyhon one wraps it. It would be far more appropriate to write a C++ bot since it would be wrapping C/C++ anyway, so having it be a C++ bot is the best way forward IMO.  

Absolutely no need to convert anything to Python! (And if we ever need to expose it through Python, that will be very easy; we'd just need to add a bot loader that can load the C++ bots and hand them over as a Python PyBot object that internally just runs the C++ functions.. that's simple.)

I think we currently don't have many C++ bots (only uniform?) so it's not clear where to put it, maybe the best place would be a top-level bots/ dir to mirror the python subdir.

**Comment by lanctot** [comment]
BTW two questions:

1. Do we know that PubEval compiles using modern compilers on its own?
2. What's the license it uses?

**Comment by jamesdfrost** [comment]
The C++ code is really simple, and should be no problem to compile, its basically an implementation of a hard coded feed forward neural network with pre-configured weights, using the raw board position as inputs with P1 pieces as +ve integers and P2 pieces as negative. 

In terms of license, Tesauro published this as "Source code is now publicly available" in 1993, link below, before the time of open source licenses. I'm presuming this is OK to use for this project, but interested in views. 

https://bkgm.com/rgb/rgb.cgi?view+610

**Comment by jamesdfrost** [comment]
I'm just starting to look into the implementation of this. PubEval is based on evaluating the strength of a particular state, rather than an action, so what I'm going to need to do is get a full list of all the possible next states following a dice roll, and then pick the state with the highest value. 

Is there an easy way of getting a list of next possible states from a game, or is this something I'll need to implement within backgammon.cc? Just looking for the cleanest and most "OpenSpiel" way of doing this.

I've also been playing with the DQN algorithm and backgammon, and not getting great results (episode rewards <0.1 against a random opponent, and in some cases negative) so also keen to implement a search based backup operator with a value net (similar to DQN approach but with state values rather than action values, as per @lanctot suggestion here: https://github.com/deepmind/open_spiel/issues/58#issuecomment-532412871) which would also benefit from this.

**Comment by lanctot** [comment]
Hi @jamesdfrost , closing this one now as it's been open for a while and I want to use the Issues for actual outstanding issues.
