### ISSUE TITLE
Can I install open_spiel on Windows?

### ISSUE THREAD

**Issue by lmh-leo** [deepmind/open_spiel#745]
thanks!

**Comment by lanctot** [comment]
Hi @lmh-leo, 

We have very limited support on Windows. The answer currently is yes, but it has to be through WSL, see the instructions here: https://github.com/deepmind/open_spiel/blob/master/docs/windows.md. 

However, there is nothing truly Linux-specific in the core of the library. Most of OpenSpiel should be able to be properly supported on Windows (at least under Cygwin, possibly fully eventually).

It would be great to finally have "real" support for Windows, but it has been a low-priority item for some time. If there is enough demand, though, hopefully this is something someone can look into. It would make a wonderful contribution!

**Comment by lanctot** [comment]
Quick update. I was curious, so I started looking into this. 

Turns out we actually have very few real Linux / MacOS dependencies. Outside of the optional parts of OpenSpiel (like HIGC which we could turn off), there are really only two "real" ones: the UCI chess bot Linux style pipes, and the utils/file.cc wrapper (which seems very easy to support on Windows and might even work already).

So I installed Cygwin on my Windows 10 install and tried that route route would be easy.. and it was going quite fabulously until I found out that abseil is not supported from Cygwin. :( This is too bad, because it looked like it was going to be an easy win. Looking at [abseil's support page](https://abseil.io/docs/cpp/platforms/platforms), they do support MSVC 2015 Update 3 and MSVC 2017. I haven't worked with Visual Studio since ~2002 so this would take me quite some time (is it even free?) Anyway, I could sure use some help with it, so please reach out if you're willing to help.

Also Windows builds are supported by [cibuildwheel](https://github.com/pypa/cibuildwheel), the package we use to create the binary wheels, so once we get it working it should be possible to distributed via pip on Windows. Though I'm not sure that those docker images / build environments support the MSVC compiler.

**Comment by lanctot** [comment]
Good news: I managed to get OpenSpiel compiled on Windows 10 in Visual Studio Community Edition! All the tests are built, and the example runs natively. The Python extension is also built and was able to be loaded by Python 3.9 and run some games.

It took many small changes to get it to compile and run in Windows, which I will submit over the coming weeks. It looks like we will be able to support Windows from source within the next month or two. I hope full support via pip/PyPI can follow (hopefully shortly) thereafter.

I'll update this thread when master is Windows-ready.

**Comment by lanctot** [comment]
Ok you can now install OpenSpiel on Windows 10 using Visual Studio community edition. For instructions, see here: https://github.com/deepmind/open_spiel/blob/master/docs/windows.md

**Comment by ThorvaldAagaard** [comment]
I have just tried to follow the instructions for installing on windows in 
https://github.com/deepmind/open_spiel/blob/master/docs/windows.md

`
git clone -b '20211102.0' --single-branch --depth 1 https://github.com/abseil/abseil-cpp.git open_spiel\abseil-cpp

git clone -b 'develop' --single-branch --depth 1 https://github.com/jblespiau/dds.git open_spiel\games\bridge\double_dummy_solver
`

The branch names should not be in quotes, and after correcting that clone worked ok

After cloning the file CMakeLists.txt was located in D:\github\open_spiel\open_spiel (I did clone from D:\github)

When opening Visual Studion CMake and running Build All all compiled and linked fine

Now I just need to figure out how to use it fromn Python as I get this error:

D:\github\open_spiel\open_spiel>py test.py
Traceback (most recent call last):
  File "D:\github\open_spiel\open_spiel\test.py", line 1, in <module>
    import pyspiel
ModuleNotFoundError: No module named 'pyspiel'

**Comment by lanctot** [comment]
Hi @ThorvaldAagaard, 

Thanks! I guess the single quotes worked in my case because I was using PowerShell? I'm not sure. Can you submit a PR fix to the instructions to remove them?

For the Python module, I only tested it when I ran Python from the same directory (which, I believe, was `open_spiel\out\build\x64-Debug\python`). On Linux and MacOS, if you add this directory to `PYTHONPATH` as described on [this page](https://github.com/deepmind/open_spiel/blob/master/docs/install.md) then it gets searched upon import. I'm not sure if there is an equivalent on Windows.

**Comment by ThorvaldAagaard** [comment]
@lanctot
I will create a PR, and is testing the description at the moment

You are right that Quotes are ignored when using PowerShell, but it works fine without them, so I will remove it.

I have tested the PYTHONPATH and will add a description for windows

When I test the other scripts in open_spiel\python\examples not all of them are working, but it is not clear to me if all should work, and waht the expected output should be. Some are missing Python-packages and I have added a description of how to install these

**Comment by lanctot** [comment]
Ah yes, that is (probably) expected. This Windows support is super new and the extent to which I have tested this so far is to cobfirm that the C++ example runs, that pyspiel can be imported, a game can be created, and a few legal moves can be applied :) 

So this is quite experimental for the moment. Please vontinue to report any breakage.

> @lanctot Will you have a look at my PR (First time I made a PR)

Absolutely! I will take a look on Monday. In the mean time, thanks for submitting it and welcome to the wonderful world of open-source. :)

**Comment by ThorvaldAagaard** [comment]
I am trying the first example using python

![image](https://user-images.githubusercontent.com/10560652/148650374-4ae2d19a-351a-462e-bee0-b72ec4e289e1.png)

And getting this error
  File "<My local dir>\open_spiel\open_spiel\python\examples\example.py", line 26, in <module>
    from open_spiel.python import games  # pylint: disable=unused-import
ModuleNotFoundError: No module named 'open_spiel'

Any suggestions about how I can build the module open_spiel  ?

**Comment by lanctot** [comment]
Ah yes this is because there are two paths you must add to PYTHONPATH. The first one is the location of the module. The second one is the root of OpenSpiel so it can find all the other modules. See the link to the Linux install instructions I posted in a previous message for how to set the PYTHONPATH in Linux, you need the same two paths in Windows.

**Comment by ThorvaldAagaard** [comment]
I did add two paths, but probably got the one to root wrong assuming it was the Python directory I should add and not root. Seems to be working now

**Comment by marcelpetran** [comment]
Hello, I'm trying installation through Visual Studio CE as recommended. but when I'm trying to build it I'm getting error with LINKER

```
[1/1] Linking CXX shared module python\pyspiel.pyd
  FAILED: python/pyspiel.pyd 
  cmd.exe /C "cd . && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_dll --intdir=python\CMakeFiles\pyspiel.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\pyspiel.rsp  /out:python\pyspiel.pyd /implib:python\pyspiel.lib /pdb:python\pyspiel.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL  && cd ."
  LINK Pass 1: command "C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\pyspiel.rsp /out:python\pyspiel.pyd /implib:python\pyspiel.lib /pdb:python\pyspiel.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL /MANIFEST /MANIFESTFILE:python\CMakeFiles\pyspiel.dir/intermediate.manifest python\CMakeFiles\pyspiel.dir/manifest.res" failed (exit code 1146) with the following output:
  Microsoft (R) Incremental Linker Version 14.35.32217.1
  
  Copyright (C) Microsoft Corporation.  All rights reserved.
  
  
  
C:\Users\mpetr\open_spiel\open_spiel\out\build\x64-Debug\LINK : fatal error LNK1146: no argument specified with option '/LIBPATH:'
```
All other test/links are fine. Only difference is that I'm using python 3.10
All requirements are met for python libs.
My PYTHONPATH is set correctly.

Any idea what could be wrong?
