### ISSUE TITLE
Unable to run example on different games

### ISSUE THREAD

**Issue by ai-gamer** [deepmind/open_spiel#75]
I want to run cfr_example.py on different games other than Kuhn poker. I changed the game name to "goofspiel". Then I got a running error like this:

RuntimeError: /Desktop/open_spiel/open_spiel/games/goofspiel.cc:313 player >= 0
player = -2, 0 = 0 

I don't know how to fix it. What mistake do I make?

**Comment by lanctot** [comment]
Ah yes that is because it is a simultaneous move game and our CFR implementations only work on turn based games (we should give a more desriptive error message in this case, we will fix this).

To get it to work, you need to transform the game to turn based. I woukd also suggest a lower number of cards than the default, i.e. start with 4. Here is an example string to use as the name of the game: https://github.com/deepmind/open_spiel/blob/89b65ac16ff906326d426c7e894130a433e6ad5a/open_spiel/integration_tests/api_test.py#L79 (you dont need impinfo or points order.. see goofspiel.h dfor what these mean)

**Comment by ai-gamer** [comment]
Great! It works.

**Comment by lanctot** [comment]
Perfect! If you don't mind, I will leave this open as a reminder to add a better error message for the case you hit (and link it to the commit when the fix is in).

**Comment by ai-gamer** [comment]
Of course. Just leave it open.
