### ISSUE TITLE
Libtorch AlphaZero at Test-Time

### ISSUE THREAD

**Issue by ngrupen** [deepmind/open_spiel#753]
Quick, and possibly silly, question regarding libtorch AZ at test-time (as in alpha_zero_torch_game_example).

alpha_zero_torch_game_example is running AZ as an MCTSBot with AZ's value network -- i.e. it inits an MCTSBot with the VPNetEvaluator instead of the standard evaluator. So it seems that (i) AZ is forced to use mcts at test-time (which requires at least max_simulations=2) and (ii) AZ uses the same number of mcts simulations (max_simulations) as its opponent.

Getting around number (ii) is pretty straightforward --> adding another flag separating, say, max_az_simulations from max_opponent_simulations, but I'm not quite sure about (i). So far, I've just been running AZ with max_simulations=2, but I'm not sure if this is equivalent to not using mcts at all. But I can confirm that changing max_simulations at test-time changes AZ's performance (especially from an early checkpoint where AZ is playing sub-optimally).

Any feedback/insight would be much appreciated!

**Comment by lanctot** [comment]
Hi @ngrupen, I might be missing something -- what's the alternative.. sampling from the prior? Minimax? What would you like to do that's different from MCTS at test time?

**Comment by ngrupen** [comment]
Hmm my thought was to evaluate performance as a function of “thinking time” — by degrading max_sims until there is virtually no look-ahead, but I’m realizing that might be misguided.

**Comment by lanctot** [comment]
No that makes perfect sense. I guess you're saying it can't go any less than 2? What does less than 2 simulations even mean? 1 simulation should be essentially sampling from the prior (since there's nothing else to compare to), e.g. no search at all. 2 simulations should still at least compare two different options and choose the best one?

Maybe you're saying the code does not support the case of max_sims=1 ? We can probably fix that, if so. Can you elaborate on what breaks when you try max_sims=1?

**Comment by ngrupen** [comment]
Yes, I guess this question comes down to sampling from the prior :) Playing with max_sims = 1 returns:
```
Spiel Fatal Error: .../mcts.cc:222 root->children.size() > 0
root->children.size() = 0, 0 = 0
```
which is also the behavior of trying to play with max_sims = 0 (and this error makes sense, since it is basically not a search anymore, as we discussed). For now, I am happy to proceed with max_sims=2, unless you think there would be enough other people interested in sampling from the prior to warrant changing this behavior.

**Comment by lanctot** [comment]
We should be supporting that case, we've used it several times in the past, and it's come in handy.

I went through the MCTS code and I think I understand why it's happening: because the root does not even add a child on the first simulation (it only gets expanded). Also it seems to me that we're not even sampling from the prior at any point, but rather always using the PUCT values. This seems like a (minor) bug: the first time we encounter a new node, the action should be _sampled_ from the prior. 

I'm off until early January, so I encourage you to fix this (and submit a PR). Here's how I suggest doing it: write a function called SampleFromPrior which does exactly that (from the node object, once it's initialized). Then, instead of the of having that check on line 222, check if max_simulations is 1. If so, return root.SampleFromPrior(). If not, continue with the rest of the function. Then, the bug fix: in ApplyTreePolicy we should use SampleFromPrior to get an action when children.size() == 0, rather than maximizing over PUCT values.

If you don't do it, I'll try to do it at some point when I'm back. If you only want to add the support for max_sims=1 but not fix that bug, that'd be great too, I can easily fix that afterward.

**Comment by ngrupen** [comment]
@lanctot Thank you for the detailed description of this fix! I took a little time off as well since we last spoke, but I am back on this -- just wanted to keep you in the loop so that we aren't double fixing :)

I've implemented SampleFromPrior() and will tackle the bug fix next. Will let you know when the PR is ready.

**Comment by lanctot** [comment]
Sounds good, thanks for the heads up because I was going to look into it soon. But I have other stuff to do as well, so will do those first. Still happy to help if you hit any snags and can imporr it whenever it is ready.

**Comment by ngrupen** [comment]
One quick question: should max_simulations=0 be handled in the same way as max_simulations=1? After SampleFromPrior() and the bug fix, max_simulations=1 samples from the evaluator as expected, but now max_simulations=0 seg faults because there is no check on line 222 anymore.

Changing the if statement to be an or over both 0 and 1 seems to fix it, but I'm not sure if there are unintended consequences of that that I am missing.

**Comment by lanctot** [comment]
Yeah I think max_simulations as 0 or 1 can be handled in the same way (where 0 is just a special case for convenience). That sounds fine to me. I will take a deeper look when I see the code, so I encourage you to submit the PR and we can iterate on it if necessary. Thanks for doing this!

**Comment by ngrupen** [comment]
@lanctot Just submitted PR #760 with proposed fix. Let me know what you think!
