### ISSUE TITLE
Low Depth - High Breadth Game

### ISSUE THREAD

**Issue by BedirT** [deepmind/open_spiel#768]
Do we have any low-depth high breadth games implemented in the library?

I was thinking of something like [Cheat](https://gamerules.com/rules/bullshit-card-game/) for two-player. 

I have a clean implementation I probably attempt to convert to open_spiel sometime soon, wanted to see if we have anything in this area, as I see the research on this type of game is not that wide-variety.

**Comment by jhtschultz** [comment]
Hi! One thing that might be worth looking into is Gambit (http://www.gambit-project.org/gambit14/index.html). It's been a bit since I've used Gambit so you'd have to consult their docs, but it lets you do cool things like construct synthetic game trees. You can write a script to build a game tree and use the branching factor to control depth vs breadth.

Once you construct an EFG game and store it in a `.efg` file, then you can run it as an OpenSpiel game. This is supported through C++ (https://github.com/deepmind/open_spiel/blob/master/open_spiel/games/efg_game.h) and Python (https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/examples/gambit_example.py).

Let me know how it works if you do go this route!
