### ISSUE TITLE
Inquiry about game terminal nodes utility

### ISSUE THREAD

**Issue by ai-gamer** [deepmind/open_spiel#79]
For game like goofspiel, there could be two ways to determine the utility of terminal nodes. 
1. the final win, draw, lose 
2. the difference of chance card value wins by each player

It seems the repository only support the first way now. Will it be helpful to add the second way for game like this?

**Comment by lanctot** [comment]
Yes, I would love it if we supported this as an option for Goofspiel! (Maybe default to the win/loss game). I

Turns out that the game play and strategies are fairly different. See  https://dke.maastrichtuniversity.nl/m.winands/documents/wcg13-smmcts.pdf -- where we ran MCTS on both games. In that paper, I called (2) the "points difference Goofspiel" and it turns it can be solved using dynamic programming (see https://www.semanticscholar.org/paper/Computer-Solution-to-the-Game-of-Pure-Strategy-Rhoads-Bartholdi/c1e3ab6fe16f634f0a9a73642a6f3f6318971e6e .. would be neat if we can reproduce this result in OpenSpiel!)

**Comment by lanctot** [comment]
@ai-gamer : if you have not started on this, let me know and I can do it. (It's gotten me excited about finally fixing the value iteration to also handle simultaneous move games since we have LP solving now, and can remove it from the call for contributions.)

**Comment by ai-gamer** [comment]
@lanctot : I don't fully understand what you mean in the (). I started to work on it. Since I am not familiar with c++, it will take me a while. If it's urgent, maybe you can do it. I will still try to do it myself to get familiar with the repository.

**Comment by lanctot** [comment]
No worries! Definitely not urgent. I will wait until it is in.

The other thing is: our implementation of value iteration currently does not support simultaneous moves. But I can still fix that regardless, so it is unrelated.
