### ISSUE TITLE
Requested Observer type not available for kNone and kSinglePlayer

### ISSUE THREAD

**Issue by kimyoonduk** [deepmind/open_spiel#810]
I have a local build that I'm testing out and I'm getting errors for single player games.

This is the error I get when trying to run the python package via rl_envionment.Environment('blackjack'):

```
[ValueError: observation_tensor not supported by blackjack]()
```

I also found that I get these errors during playthroughs when I'm running build_and_run_tests.sh

```
OpenSpiel exception: Requested Observer type not available: IIGObservationType{perfect_recall=false, public_info=true, private_info=kNone}
OpenSpiel exception: Requested Observer type not available: IIGObservationType{perfect_recall=false, public_info=false, private_info=kSinglePlayer}
```

**Comment by lanctot** [comment]
Hi @kimyoonduk, 

Yes, looking at the blackjack implementation, it seems to not have any observation or information state tensors defined, which means you (currently) can't use it for RL experiments with neural networks. This sometimes happens when we get contributions of games that are not complete, but e.g. it could still be used for some tabular methods. 

I think in the case of blackjack, it should be fairly easy to add a simple observation tensor and I'd be happy to help describe how to do that if you're interested. Thanks for bringing it to our attention because if you don't add it now we'll probably do it eventually.
