### ISSUE TITLE
Implementing NSFP for custom simultaneous game with non homogenous agents.

### ISSUE THREAD

**Issue by hhlei** [deepmind/open_spiel#816]
I'm a little confused on how to implement NSFP for simultaneous games. In the examples, NSFPpolicies's actionProbabilities method relies on state.currentPlayer(). But in simultaneous games (in my game at least), the curr_player_ is always kSimultaneousID. How exactly does the right obs/rewards get routed to the right NSFPpolicy? Do I have to define special behavior in the game to make sure that things happen in the right order?

**Comment by lanctot** [comment]
Best way to do this is to used the turn-based simultaneous game wrapper. There should be some examples (maybe in nfsp_test or game_transforms). If not I am quite sure cfr_test would have some exampled of how to use it.

The observation and info state functions have players as arguments (the observing player). You can check goofspiel, oshi-zumo, or Markov soccer for examples.

**Comment by hhlei** [comment]
Thanks for the help! Quick question: in Goofspiel, the game class has member variables default_observer_, info_state_observer_ etc, that are labeled as "old observation api". What is the newer way to do it?

**Comment by lanctot** [comment]
Hi @hhlei, 

Do you mean [this comment](https://github.com/deepmind/open_spiel/blob/550f2fba696428606023e31ccd97cbf24c4a5daa/open_spiel/games/goofspiel.h#L168)? I think that comment is referring just to the first one "default_observer". That observer is used to implement the "old" observation API.

OpenSpiel supports a "new" (it's almost already 2 years old! haha) observation API. Examples of this API can be seen in Leduc and Goofspiel. It uses the observer objects to more cleanly fill up the observation and information state tensors. 

Not all games use the observation because many games have not been converted to use it. And also new games still use the "old" format of just filling the tensor manually (see e.g. "bargaining" which I added recently). There is no requirement to use the observation API, so I'm not sure referring to them as "old" versus "new" makes much sense at this point. I'd probably use the terminology: uses the observation API (e.g. Leduc, Goofspiel) versus does not use the observation API (e.g. bargaining).

**Comment by lanctot** [comment]
Any update on this? If not I am inclined to close it.
