### ISSUE TITLE
Test 167 (pytorch/rcfr_pytorch_test.py) failed when building from source on mac os

### ISSUE THREAD

**Issue by VitamintK** [deepmind/open_spiel#833]
Building from source from master (haven't done it in a while, so I could definitely be doing something wrong?)

Get the error:

```
FAIL: test_rcfr_functions (__main__.RcfrTest)
RcfrTest.test_rcfr_functions
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../open_spiel/python/pytorch/rcfr_pytorch_test.py", line 470, in test_rcfr_functions
    self.assertLess(pyspiel.nash_conv(_GAME, average_profile), 0.91)
AssertionError: 1.4048300405772975 not less than 0.91
```

What I did:
- pull latest master
-  ./install.sh
- pip install -r requirements.txt
- ./open_spiel/scripts/build_and_run_tests.sh

and that's when the test fails.

Anyone else run into this before?  All other tests pass just fine.

**Comment by lanctot** [comment]
This was one test in a series that I changed recently when upgrading pytorch versions. 

Can I check which version of pytorch you are using?

**Comment by lanctot** [comment]
Here is the commit with those changes, if it helps: 
https://github.com/deepmind/open_spiel/commit/5111a3591df9f26a7b6c11d68e3660b1aedd1293

**Comment by VitamintK** [comment]
I'm apparently still on pytorch 1.7.0

**Comment by VitamintK** [comment]
confirmed that upgrading to the expected pytorch passes the test (and it was consistently failing before):

`pip install --upgrade torch==1.11.0`

`./open_spiel/scripts/build_and_run_tests.sh --test_only="rcfr"`

passes.

**Comment by VitamintK** [comment]
So is there a bug where running the install scripts should have updated pytorch and didn't? (I didn't set any env vars when running the scripts, so they are all on auto.) Or if that's expected behavior, then is there a bug where the pytorch tests shouldn't have run for me but they did?

**Comment by lanctot** [comment]
This is all intended behavior, it's just a rare case because the change in the commit above caused an incompatibility with the old version of PyTorch.

Last year, we made most of the Python packages optional dependencies. This is because most of the python functionality is "extra" and we didn't want to cause python dependency nightmares for any projects that depend on us for mostly optional features (we were pegging versions quite strongly). So now we only have 4 real required python packages, and the "canonical versions" for the optional ones are listed in scripts/python_extra_deps.sh.

Our build and run test script do not install these optional extra deps, it (mostly) detects them and enables the right python tests based on what's found. It's only on github Actions CI that we actually install and upgrade everything to those python versions listed in the extra deps.

I think this is the currently the best compromise, because we don't want to be forceful about upgrading user's python package versions locally, but it does mean breakage in these rare cases.

**Comment by VitamintK** [comment]
ok, that sounds reasonable, thanks for the reponse! Is it not desirable or not feasible to check the user's pytorch version before deciding whether or not to run the pytorch tests?

My 2 cents: It feels to me like the behavior I encountered is pretty bad (since there's no error message or anything indicating what was wrong) and I don't see why it would be rare: anytime OpenSpiel upgrades a dependency, there's a good chance there can be backwards-incompatible changes. It's fortunate that the test failed here, otherwise the issue would have been much more insidious if I was running pytorch code and it wasn't working.

I guess this means that running and failing the test was actually good, so my solution above is actually undesirable.  Maybe the best and easiest solution is just to add a line to `install.md` about manually running `pip install --upgrade` the extra dependencies if using python?

**Comment by lanctot** [comment]
Yeah I thought it would be more common myself, but turns out most projects tend to be backward-compatible. This is only the second time something like this has happened since August 2019, and we upgrade the versions 2-3 times per year (and the other time wasn't even python packages, it was that we upgraded the version of abseil).

I like the idea of mentioning the versions and pointing to that file in the install docs. Do you want to submit a PR for it?
