### ISSUE TITLE
Nim game not available

### ISSUE THREAD

**Issue by sagebei** [deepmind/open_spiel#897]
Nim game is on the game list at: [available games](https://openspiel.readthedocs.io/en/latest/games.html). But it is not available in `pyspiel.registered_games()`.

**Comment by lanctot** [comment]
Hi @sagebei, 

Are you using OpenSpiel via colabor via the pip binary installation? If so, then it's because that installs the latest release (1.1.1) which did not contain Nim since it was only recently added to master (last month). We are planning a release this month, though-- hopefully within the next week or two. Nim will then be available in that release. Until then, you need to build from source.

**Comment by sagebei** [comment]
Hi @lanctot 

Yes, I am using the pip installation. I will reinstall from the source then. Thank you for your prompt reply!

**Comment by lanctot** [comment]
No problem. Remember to uninstall the pip version first (`python3 -m pip uninstall open_spiel`) otherwise your Python interpreter will likely find that one instead :) Keep an eye out for the release if you want to switch back!
