### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by sagebei** [deepmind/open_spiel#898]
Hi,

I was installing the open_spiel library by building from source and following the instructions [here](https://github.com/deepmind/open_spiel/blob/master/docs/install.md#configuring-conditional-dependencies). Everything was fine until I run the last command, which raised the error: `ImportError: /home/bei/PycharmProjects/open_spiel/build/python/pyspiel.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv
`. I have tried multiple times with different options, but unfortunately none of them worked. 

1. ./install.sh
2. virtualenv -p python3 venv
3. source venv/bin/activate
4. curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
5. python3 get-pip.py
6. pip3 install --upgrade pip
7. pip3 install --upgrade setuptools testresources
8. pip3 install -r requirements.txt
9. ./open_spiel/scripts/build_and_run_tests.sh

**Comment by lanctot** [comment]
Did the build work and you are having the problem when you try to import pyspiel, or did the build fail?

Can you tell me what platform you are using? (OS and version + python version)?

**Comment by sagebei** [comment]
The build worked fine. The problem occurred when I run the test. I cannot import pyspiel as well (`PYTHONPATH `was added to the virtual environment). 

I am using python 3.9.7 and Ubuntu 22.04.1 LTS

**Comment by lanctot** [comment]
Can you try with skipping steps 4 & 5 above and using `python3 -m pip` instead of `pip3` for steps 6-8?

Seems like others have had similar issues with pybind11 (are you using Conda?), so if that doesn't work see this thread for more info and some things to try: https://github.com/pybind/pybind11/issues/3623

**Comment by sagebei** [comment]
Hi @lanctot 

Thank you. I tried the method you mentioned, but it did not work. Luckily, **that problem did not arise on another machine**. I am trying out the Nim game and found that the state representation and action representation are hard to comprehend, as shown below. Is there any documentation that shows how the game is represented? 

`initial_state.observation_tensor() -->
[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]`

`initial_state.legal_actions()
[0, 1, 2, 3, 5, 6, 7, 9, 10, 11, 14, 15, 18, 19, 23, 27]`

**Comment by lanctot** [comment]
Ah yes, the actions in OpenSpiel are all integers and for games with structured action spaces like this, it can be hard to see exactly what each means. You can always call `state.action_to_string(player_id, action)` to get a more friendly string representation. For programmatic access you need to expose per-game converters. Here is an example of them for Backgammon: https://github.com/deepmind/open_spiel/blob/78feab4292a3bffc33c3c0f561cb95ea0c895619/open_spiel/python/pybind11/games_backgammon.cc#L38, which wraps the CheckerMove structure in the Backgammon game. 

To get a string representation of the state, you can also just `print(state)`.

The observation tensor is documented in each individual game. For example, here is the one for Nim: https://github.com/deepmind/open_spiel/blob/78feab4292a3bffc33c3c0f561cb95ea0c895619/open_spiel/games/nim.cc#L193

Lastly this tutorial may help with some of the basic API/features: https://www.youtube.com/watch?v=8NCPqtPwlFQ

We are currently building a general way to expose stuctured actions (where each is represented as a vector). This will be coming soon (in our next major release) so that there is a more comprehensive and streamlined way to deal with the actions.

**Comment by sagebei** [comment]
Thank you very much! That is very helpful. I did not know we can do like that. I will check out that video which seems to be informative.
